package main

import (
	"log"
	"strings"
)

type country struct {
	Name string
	Code string
}

func loadCountries() {
	const (
		csvPath          = "/Users/andy/Downloads/GeoIPCountryWhois.csv"
		countryCodeIndex = 4
		countryNameIndex = 5
	)

	countries = []country{}
	records := loadCSV(csvPath)
	for _, v := range records {
		countries = append(countries, country{Name: v[countryNameIndex], Code: v[countryCodeIndex]})
	}

	log.Println(countries)
}

func caseInsenstiveEqual(a, b string) bool {
	return strings.EqualFold(a, b)
}

func findCountry(location string) string {
	separators := separators()
	res := ""
	for _, s := range separators {
		res = findCountryS(location, s)
		if res != "" {
			break
		}
	}

	return res
}

func findCountryS(location, separator string) string {
	val := ""
	res := ""

	parts := strings.Split(location, separator)
	for _, p := range parts {
		val = strings.TrimSpace(p)
		res = findCountryString(val)
		if res != "" {
			break
		}
	}

	return res
}

func findCountryString(location string) string {
	res := ""
	for _, v := range countries {
		if caseInsenstiveEqual(location, v.Name) {
			log.Println("Found country", v.Name, "in location", location)
			res = v.Code
			break
		}
	}

	return res
}

var countries = []country{
	{Name: "GLOBAL", Code: "WW"},
	{Name: "Afghanistan", Code: "AF"},
	{Name: "Aland Island", Code: "AX"},
	{Name: "Albania", Code: "AL"},
	{Name: "Algeria", Code: "DZ"},
	{Name: "American Samoa", Code: "AS"},
	{Name: "Andorra", Code: "AD"},
	{Name: "Angola", Code: "AO"},
	{Name: "Anguilla", Code: "AI"},
	{Name: "Antarctica", Code: "AQ"},
	{Name: "Antigua and Barbuda", Code: "AG"},
	{Name: "Argentina", Code: "AR"},
	{Name: "Armenia", Code: "AM"},
	{Name: "Aruba", Code: "AW"},
	{Name: "Australia", Code: "AU"},
	{Name: "Austria", Code: "AT"},
	{Name: "Azerbaijan", Code: "AZ"},
	{Name: "Bahamas", Code: "BS"},
	{Name: "Bahrain", Code: "BH"},
	{Name: "Bangladesh", Code: "BD"},
	{Name: "Barbados", Code: "BB"},
	{Name: "Belarus", Code: "BY"},
	{Name: "Belgium", Code: "BE"},
	{Name: "Belize", Code: "BZ"},
	{Name: "Benin", Code: "BJ"},
	{Name: "Bermuda", Code: "BM"},
	{Name: "Bhutan", Code: "BT"},
	{Name: "Bolivia", Code: "BO"},
	{Name: "Bosnia and Herzegovina", Code: "BA"},
	{Name: "Botswana", Code: "BW"},
	{Name: "Bouvet Island", Code: "BV"},
	{Name: "British Virgin Islands", Code: "VG"},
	{Name: "Brazil", Code: "BR"},
	{Name: "British Indian Ocean Territory", Code: "IO"},
	{Name: "Brunei Darussalam", Code: "BN"},
	{Name: "Bulgaria", Code: "BG"},
	{Name: "Burkina Faso", Code: "BF"},
	{Name: "Burundi", Code: "BI"},
	{Name: "Cambodia", Code: "KH"},
	{Name: "Cameroon", Code: "CM"},
	{Name: "Canada", Code: "CA"},
	{Name: "Cape Verde", Code: "CV"},
	{Name: "Cayman Islands", Code: "KY"},
	{Name: "Central African Republic", Code: "CF"},
	{Name: "Chad", Code: "TD"},
	{Name: "Chile", Code: "CL"},
	{Name: "China", Code: "CN"},
	{Name: "Hong Kong, SAR China", Code: "HK"},
	{Name: "Macao, SAR China", Code: "MO"},
	{Name: "Christmas Island", Code: "CX"},
	{Name: "Cocos(Keeling) Islands", Code: "CC"},
	{Name: "Colombia", Code: "CO"},
	{Name: "Comoros", Code: "KM"},
	{Name: "Congo (Brazzaville)", Code: "CG"},
	{Name: "Congo, (Kinshasa)", Code: "CD"},
	{Name: "Cook Islands", Code: "CK"},
	{Name: "Costa Rica", Code: "CR"},
	{Name: "Côte dIvoire", Code: "CI"},
	{Name: "Croatia", Code: "HR"},
	{Name: "Cuba", Code: "CU"},
	{Name: "Cyprus", Code: "CY"},
	{Name: "Czech Republic", Code: "CZ"},
	{Name: "Denmark", Code: "DK"},
	{Name: "Djibouti", Code: "DJ"},
	{Name: "Dominica", Code: "DM"},
	{Name: "Dominican Republic", Code: "DO"},
	{Name: "Ecuador", Code: "EC"},
	{Name: "Egypt", Code: "EG"},
	{Name: "El Salvador", Code: "SV"},
	{Name: "Equatorial Guinea", Code: "GQ"},
	{Name: "Eritrea", Code: "ER"},
	{Name: "Estonia", Code: "EE"},
	{Name: "Ethiopia", Code: "ET"},
	{Name: "Falkland Islands (Malvinas)", Code: "FK"},
	{Name: "Faroe Islands", Code: "FO"},
	{Name: "Fiji", Code: "FJ"},
	{Name: "Finland", Code: "FI"},
	{Name: "France", Code: "FR"},
	{Name: "French Guiana", Code: "GF"},
	{Name: "French Polynesia", Code: "PF"},
	{Name: "French Southern Territories", Code: "TF"},
	{Name: "Gabon", Code: "GA"},
	{Name: "Gambia", Code: "GM"},
	{Name: "Georgia", Code: "GE"},
	{Name: "Germany", Code: "DE"},
	{Name: "Ghana", Code: "GH"},
	{Name: "Gibraltar", Code: "GI"},
	{Name: "Greece", Code: "GR"},
	{Name: "Greenland", Code: "GL"},
	{Name: "Grenada", Code: "GD"},
	{Name: "Guadeloupe", Code: "GP"},
	{Name: "Guam", Code: "GU"},
	{Name: "Guatemala", Code: "GT"},
	{Name: "Guernsey", Code: "GG"},
	{Name: "Guinea", Code: "GN"},
	{Name: "Guinea-Bissau", Code: "GW"},
	{Name: "Guyana", Code: "GY"},
	{Name: "Haiti", Code: "HT"},
	{Name: "Heard and Mcdonald Islands", Code: "HM"},
	{Name: "Holy See (Vatican City State)", Code: "VA"},
	{Name: "Honduras", Code: "HN"},
	{Name: "Hungary", Code: "HU"},
	{Name: "Iceland", Code: "IS"},
	{Name: "India", Code: "IN"},
	{Name: "Indonesia", Code: "ID"},
	{Name: "Iran", Code: "IR"},
	{Name: "Iraq", Code: "IQ"},
	{Name: "Ireland", Code: "IE"},
	{Name: "Isle of Man", Code: "IM"},
	{Name: "Israel", Code: "IL"},
	{Name: "Italy", Code: "IT"},
	{Name: "Jamaica", Code: "JM"},
	{Name: "Japan", Code: "JP"},
	{Name: "Jersey", Code: "JE"},
	{Name: "Jordan", Code: "JO"},
	{Name: "Kazakhstan", Code: "KZ"},
	{Name: "Kenya", Code: "KE"},
	{Name: "Kiribati", Code: "KI"},
	{Name: "Korea (North)", Code: "KP"},
	{Name: "Korea (South)", Code: "KR"},
	{Name: "Kuwait", Code: "KW"},
	{Name: "Kyrgyzstan", Code: "KG"},
	{Name: "Lao PDR", Code: "LA"},
	{Name: "Latvia", Code: "LV"},
	{Name: "Lebanon", Code: "LB"},
	{Name: "Lesotho", Code: "LS"},
	{Name: "Liberia", Code: "LR"},
	{Name: "Libya", Code: "LY"},
	{Name: "Liechtenstein", Code: "LI"},
	{Name: "Lithuania", Code: "LT"},
	{Name: "Luxembourg", Code: "LU"},
	{Name: "Macedonia", Code: "MK"},
	{Name: "Madagascar", Code: "MG"},
	{Name: "Malawi", Code: "MW"},
	{Name: "Malaysia", Code: "MY"},
	{Name: "Maldives", Code: "MV"},
	{Name: "Mali", Code: "ML"},
	{Name: "Malta", Code: "MT"},
	{Name: "Marshall Islands", Code: "MH"},
	{Name: "Martinique", Code: "MQ"},
	{Name: "Mauritania", Code: "MR"},
	{Name: "Mauritius", Code: "MU"},
	{Name: "Mayotte", Code: "YT"},
	{Name: "Mexico", Code: "MX"},
	{Name: "Micronesia", Code: "FM"},
	{Name: "Moldova", Code: "MD"},
	{Name: "Monaco", Code: "MC"},
	{Name: "Mongolia", Code: "MN"},
	{Name: "Montenegro", Code: "ME"},
	{Name: "Montserrat", Code: "MS"},
	{Name: "Morocco", Code: "MA"},
	{Name: "Mozambique", Code: "MZ"},
	{Name: "Myanmar", Code: "MM"},
	{Name: "Namibia", Code: "NA"},
	{Name: "Nauru", Code: "NR"},
	{Name: "Nepal", Code: "NP"},
	{Name: "Netherlands", Code: "NL"},
	{Name: "Netherlands Antilles", Code: "AN"},
	{Name: "New Caledonia", Code: "NC"},
	{Name: "New Zealand", Code: "NZ"},
	{Name: "Nicaragua", Code: "NI"},
	{Name: "Niger", Code: "NE"},
	{Name: "Nigeria", Code: "NG"},
	{Name: "Niue", Code: "NU"},
	{Name: "Norfolk Island", Code: "NF"},
	{Name: "Northern Mariana Islands", Code: "MP"},
	{Name: "Norway", Code: "NO"},
	{Name: "Oman", Code: "OM"},
	{Name: "Pakistan", Code: "PK"},
	{Name: "Palau", Code: "PW"},
	{Name: "Palestinian Territory", Code: "PS"},
	{Name: "Panama", Code: "PA"},
	{Name: "Papua New Guinea", Code: "PG"},
	{Name: "Paraguay", Code: "PY"},
	{Name: "Peru", Code: "PE"},
	{Name: "Philippines", Code: "PH"},
	{Name: "Pitcairn", Code: "PN"},
	{Name: "Poland", Code: "PL"},
	{Name: "Portugal", Code: "PT"},
	{Name: "Puerto Rico", Code: "PR"},
	{Name: "Qatar", Code: "QA"},
	{Name: "Réunion", Code: "RE"},
	{Name: "Romania", Code: "RO"},
	{Name: "Russian Federation", Code: "RU"},
	{Name: "Rwanda", Code: "RW"},
	{Name: "Saint - Barthélemy", Code: "BL"},
	{Name: "Saint Helena", Code: "SH"},
	{Name: "Saint Kitts and Nevis", Code: "KN"},
	{Name: "Saint Lucia", Code: "LC"},
	{Name: "Saint - Martin(French part)", Code: "MF"},
	{Name: "Saint Pierre and Miquelon", Code: "PM"},
	{Name: "Saint Vincent and Grenadines", Code: "VC"},
	{Name: "Samoa", Code: "WS"},
	{Name: "San Marino", Code: "SM"},
	{Name: "Sao Tome and Principe", Code: "ST"},
	{Name: "Saudi Arabia", Code: "SA"},
	{Name: "Senegal", Code: "SN"},
	{Name: "Serbia", Code: "RS"},
	{Name: "Seychelles", Code: "SC"},
	{Name: "Sierra Leone", Code: "SL"},
	{Name: "Singapore", Code: "SG"},
	{Name: "Slovakia", Code: "SK"},
	{Name: "Slovenia", Code: "SI"},
	{Name: "Solomon Islands", Code: "SB"},
	{Name: "Somalia", Code: "SO"},
	{Name: "South Africa", Code: "ZA"},
	{Name: "South Georgia and the South Sandwich Islands", Code: "GS"},
	{Name: "South Sudan", Code: "SS"},
	{Name: "Spain", Code: "ES"},
	{Name: "Sri Lanka", Code: "LK"},
	{Name: "Sudan", Code: "SD"},
	{Name: "Suriname", Code: "SR"},
	{Name: "Svalbard and Jan Mayen Islands", Code: "SJ"},
	{Name: "Swaziland", Code: "SZ"},
	{Name: "Sweden", Code: "SE"},
	{Name: "Switzerland", Code: "CH"},
	{Name: "Syrian Arab Republic (Syria)", Code: "SY"},
	{Name: "Taiwan", Code: "TW"},
	{Name: "Tajikistan", Code: "TJ"},
	{Name: "Tanzania", Code: "TZ"},
	{Name: "Thailand", Code: "TH"},
	{Name: "Timor - Leste", Code: "TL"},
	{Name: "Togo", Code: "TG"},
	{Name: "Tokelau", Code: "TK"},
	{Name: "Tonga", Code: "TO"},
	{Name: "Trinidad and Tobago", Code: "TT"},
	{Name: "Tunisia", Code: "TN"},
	{Name: "Turkey", Code: "TR"},
	{Name: "Turkmenistan", Code: "TM"},
	{Name: "Turks and Caicos Islands", Code: "TC"},
	{Name: "Tuvalu", Code: "TV"},
	{Name: "Uganda", Code: "UG"},
	{Name: "Ukraine", Code: "UA"},
	{Name: "United Arab Emirates", Code: "AE"},
	{Name: "United Kingdom", Code: "GB"},
	{Name: "United States of America", Code: "US"},
	{Name: "US Minor Outlying Islands", Code: "UM"},
	{Name: "Uruguay", Code: "UY"},
	{Name: "Uzbekistan", Code: "UZ"},
	{Name: "Vanuatu", Code: "VU"},
	{Name: "Venezuela", Code: "VE"},
	{Name: "Vietnam", Code: "VN"},
	{Name: "U.S. Virgin Islands", Code: "VI"},
	{Name: "Wallis and Futuna Islands", Code: "WF"},
	{Name: "Western Sahara", Code: "EH"},
	{Name: "Yemen", Code: "YE"},
	{Name: "Zambia", Code: "ZM"},
	{Name: "Zimbabwe", Code: "ZW"},
	{Name: "Hong Kong", Code: "HK"},
	{Name: "Macao", Code: "MO"},
	{Name: "Cocos Islands", Code: "CC"},
	{Name: "Republic of the Congo", Code: "CG"},
	{Name: "Democratic Republic of the Congo", Code: "CD"},
	{Name: "République de Côte d'Ivoire", Code: "CI"},
	{Name: "Falkland Islands", Code: "FK"},
	{Name: "Islas Malvinas", Code: "FK"},
	{Name: "Guiana", Code: "GF"},
	{Name: "French Southern and Antarctic Lands", Code: "TF"},
	{Name: "Kerguelen Islands", Code: "TF"},
	{Name: "St. Paul and Amsterdam islands", Code: "TF"},
	{Name: "Crozet Islands", Code: "TF"},
	{Name: "Adélie Land", Code: "TF"},
	{Name: "Scattered Islands", Code: "TF"},
	{Name: "Federal Republic of Germany", Code: "DE"},
	{Name: "Guinea Bissau", Code: "GW"},
	{Name: "Heard Island and Mcdonald Islands", Code: "HM"},
	{Name: "HIMI", Code: "HM"},
	{Name: "See of Rome", Code: "VA"},
	{Name: "Holy See", Code: "VA"},
	{Name: "Vatican City State", Code: "VA"},
	{Name: "Persia", Code: "IR"},
	{Name: "Islamic Republic of Iran", Code: "IR"},
	{Name: "Mann", Code: "IM"},
	{Name: "North Korea", Code: "KP"},
	{Name: "South Korea", Code: "KR"},
	{Name: "Korea", Code: "KR"},
	{Name: "Republic of Korea", Code: "KR"},
	{Name: "Laos", Code: "LA"},
	{Name: "Saint Barthélemy", Code: "BL"},
	{Name: "Russia", Code: "RU"},
	{Name: "Russian", Code: "RU"},
	{Name: "Saint Martin", Code: "MF"},
	{Name: "Syria", Code: "SY"},
	{Name: "Syrian Arab Republic", Code: "SY"},
	{Name: "East Timor", Code: "TL"},
	{Name: "UAE", Code: "AE"},
	{Name: "Britain", Code: "GB"},
	{Name: "England", Code: "GB"},
	{Name: "UK", Code: "GB"},
	{Name: "U.K.", Code: "GB"},
	{Name: "USA", Code: "US"},
	{Name: "NY", Code: "US"},
	{Name: "U.S.A.", Code: "US"},
	{Name: "U.S.A", Code: "US"},
	{Name: "US", Code: "US"},
	{Name: "United States", Code: "US"},
	{Name: "America", Code: "US"},
	{Name: "US Virgin Islands", Code: "VI"},
	{Name: "Viet Nam", Code: "VN"},
	{Name: "Fontenay-Trésigny", Code: "FR"},
	{Name: "Türkiye", Code: "TR"},
	{Name: "Brasil", Code: "BR"},
	{Name: "Republic of China", Code: "TW"},
	{Name: "ROC", Code: "TW"},
	{Name: "Nederlands", Code: "NL"},
	{Name: "United Kingdeon", Code: "GB"},
	{Name: "Singapoe", Code: "SG"},
	{Name: "Україна", Code: "UA"},
	{Name: "Украина", Code: "UA"},
	{Name: "Ukraina", Code: "UA"},
	{Name: "Ukrane", Code: "UA"},
	{Name: "Ukrain", Code: "UA"},
	{Name: "UA", Code: "UA"},
	{Name: "Россия", Code: "RU"},
	{Name: "Российская Федерация", Code: "RU"},
	{Name: "RU", Code: "RU"},
	{Name: "Slovenija", Code: "SI"},
	{Name: "Russia Federation", Code: "RU"},
	{Name: "Česká republika", Code: "CZ"},
	{Name: "Polska", Code: "PL"},
	{Name: "Deutschland", Code: "DE"},
	{Name: "Bosnia & Herzegovina", Code: "BA"},
	{Name: "KSA", Code: "SA"},
	{Name: "España", Code: "ES"},
	{Name: "Sllovakia", Code: "SK"},
	{Name: "United Kingdon", Code: "GB"},
	{Name: "México", Code: "MX"},
	{Name: "Méxco", Code: "MX"},
	{Name: "Czech", Code: "CZ"},
	{Name: "Latvija", Code: "LV"},
	{Name: "България", Code: "BG"},
	{Name: "România", Code: "RO"},
	{Name: "Польша", Code: "PL"},
	{Name: "Kazakstan", Code: "KZ"},
	{Name: "Morroco", Code: "MA"},
	{Name: "SouthKorea", Code: "KR"},
	{Name: "Polnad", Code: "PL"},

	{Name: "Гваделупа", Code: "GP"},
	{Name: "Canada", Code: "CA"},
	{Name: "Botsuana", Code: "BW"},
	{Name: "ワリー エ フトゥーナ諸島", Code: "WF"},
	{Name: "Territórios palestinos", Code: "PS"},
	{Name: "Burkina Fasso", Code: "BF"},
	{Name: "Santa Helena", Code: "SH"},
	{Name: "Сирийская Арабская Республика", Code: "SY"},
	{Name: "马来西亚", Code: "MY"},
	{Name: "瓦努阿图", Code: "VU"},
	{Name: "古巴", Code: "CU"},
	{Name: "Kenya", Code: "KE"},
	{Name: "Egypt", Code: "EG"},
	{Name: "Republic of Lithuania", Code: "LT"},
	{Name: "贝宁", Code: "BJ"},
	{Name: "コロンビア共和国", Code: "CO"},
	{Name: "Macau", Code: "MO"},
	{Name: "Westsahara", Code: "EH"},
	{Name: "Svalbard and Jan Mayen", Code: "SJ"},
	{Name: "Bielorrusia", Code: "BY"},
	{Name: "Sáhara Occidental", Code: "EH"},
	{Name: "Antigua et Barbuda", Code: "AG"},
	{Name: "キルギス共和国", Code: "KG"},
	{Name: "Греция", Code: "GR"},
	{Name: "Северные Марианские о-ва", Code: "MP"},
	{Name: "Saint-Vincent-et-les Grenadines", Code: "VC"},
	{Name: "ニュージーランド", Code: "NZ"},
	{Name: "Kasachstan", Code: "KZ"},
	{Name: "San Bartolomé", Code: "BL"},
	{Name: "Brunéi Darussalam", Code: "BN"},
	{Name: "Équateur", Code: "EC"},
	{Name: "Catar", Code: "QA"},
	{Name: "莱索托", Code: "LS"},
	{Name: "Bangladesch", Code: "BD"},
	{Name: "India", Code: "IN"},
	{Name: "Austria", Code: "AT"},
	{Name: "Maldivas", Code: "MV"},
	{Name: "Chili", Code: "CL"},
	{Name: "Нигерия", Code: "NG"},
	{Name: "乌克兰", Code: "UA"},
	{Name: "加蓬", Code: "GA"},
	{Name: "北马里亚纳群岛", Code: "MP"},
	{Name: "Kongo", Code: "CD"},
	{Name: "St. Lucia", Code: "LC"},
	{Name: "Territorios Australes Franceses", Code: "TF"},
	{Name: "Costa do Marfim", Code: "CI"},
	{Name: "Islândia", Code: "IS"},
	{Name: "Босния", Code: "BA"},
	{Name: "アルバ島", Code: "AW"},
	{Name: "Liechtenstein", Code: "LI"},
	{Name: "United Kingdom", Code: "GB"},
	{Name: "Alemania", Code: "DE"},
	{Name: "Îles Féroé", Code: "FO"},
	{Name: "スーダン共和国", Code: "SD"},
	{Name: "フィンランド共和国", Code: "FI"},
	{Name: "バハマ国", Code: "BS"},
	{Name: "トケラウ諸島", Code: "TK"},
	{Name: "Ilhas Coco", Code: "CC"},
	{Name: "Timor-Leste", Code: "TL"},
	{Name: "Nouvelle-Calédonie", Code: "NC"},
	{Name: "Bangladesh", Code: "BD"},
	{Name: "U.S. Minor Outlying Islands", Code: "UM"},
	{Name: "Gana", Code: "GH"},
	{Name: "Ilha de Man", Code: "IM"},
	{Name: "ЮАР", Code: "ZA"},
	{Name: "Хорватия", Code: "HR"},
	{Name: "塞舌尔群岛", Code: "SC"},
	{Name: "United States", Code: "US"},
	{Name: "ジンバブエ共和国", Code: "ZW"},
	{Name: "Иордания", Code: "JO"},
	{Name: "Острова Херд и Макдональд", Code: "HM"},
	{Name: "Гернси", Code: "GG"},
	{Name: "Puerto Rico", Code: "PR"},
	{Name: "Marshall Islands", Code: "MH"},
	{Name: "Italie", Code: "IT"},
	{Name: "ラトビア共和国", Code: "LV"},
	{Name: "ソロモン諸島", Code: "SB"},
	{Name: "Zypern", Code: "CY"},
	{Name: "Timor Oriental", Code: "TL"},
	{Name: "ギニア共和国", Code: "GN"},
	{Name: "Turkmenistan", Code: "TM"},
	{Name: "Colombie", Code: "CO"},
	{Name: "レソト王国", Code: "LS"},
	{Name: "西サハラ", Code: "EH"},
	{Name: "Гондурас", Code: "HN"},
	{Name: "Senegal", Code: "SN"},
	{Name: "Congo Democrático", Code: "CD"},
	{Name: "Chine", Code: "CN"},
	{Name: "Остров Доминика", Code: "DM"},
	{Name: "伊朗伊斯兰共和国", Code: "IR"},
	{Name: "萨尔瓦多", Code: "SV"},
	{Name: "亚美尼亚", Code: "AM"},
	{Name: "Saint-Pierre et Miquelon", Code: "PM"},
	{Name: "ボスニア・ヘルツェゴビナ共和国", Code: "BA"},
	{Name: "グアテマラ", Code: "GT"},
	{Name: "Arábia Saudita", Code: "SA"},
	{Name: "Estônia", Code: "EE"},
	{Name: "Тунис", Code: "TN"},
	{Name: "Виргинские о-ва (США)", Code: "VI"},
	{Name: "Дания", Code: "DK"},
	{Name: "Komoren", Code: "KM"},
	{Name: "Faroe Islands", Code: "FO"},
	{Name: "Islas Heard y McDonald", Code: "HM"},
	{Name: "Ciudad del Vaticano", Code: "VA"},
	{Name: "ラオス", Code: "LA"},
	{Name: "セントヘレナ", Code: "SH"},
	{Name: "Новая Зеландия", Code: "NZ"},
	{Name: "新西兰", Code: "NZ"},
	{Name: "巴拉圭", Code: "PY"},
	{Name: "Greenland", Code: "GL"},
	{Name: "Islas Malvinas", Code: "FK"},
	{Name: "モロッコ王国", Code: "MA"},
	{Name: "Guiné", Code: "GN"},
	{Name: "斯洛伐克共和国", Code: "SK"},
	{Name: "捷克共和国", Code: "CZ"},
	{Name: "关岛", Code: "GU"},
	{Name: "Eritrea", Code: "ER"},
	{Name: "Belarus", Code: "BY"},
	{Name: "Tayikistán", Code: "TJ"},
	{Name: "Ouganda", Code: "UG"},
	{Name: "サンピエール島・ミクロン島", Code: "PM"},
	{Name: "Американское Самоа", Code: "AS"},
	{Name: "哈萨克斯坦", Code: "KZ"},
	{Name: "Kolumbien", Code: "CO"},
	{Name: "Central African Republic", Code: "CF"},
	{Name: "モナコ", Code: "MC"},
	{Name: "ガイアナ", Code: "GY"},
	{Name: "Somália", Code: "SO"},
	{Name: "Заир", Code: "CD"},
	{Name: "Британские Виргинские о-ва", Code: "VG"},
	{Name: "Latvia", Code: "LV"},
	{Name: "Egipto", Code: "EG"},
	{Name: "Anguila", Code: "AI"},
	{Name: "キプロス共和国", Code: "CY"},
	{Name: "Кувейт", Code: "KW"},
	{Name: "Taiwan", Code: "TW"},
	{Name: "Fidschi", Code: "FJ"},
	{Name: "Emiratos Árabes Unidos", Code: "AE"},
	{Name: "Turquía", Code: "TR"},
	{Name: "Indonésie", Code: "ID"},
	{Name: "ヨルダン・ハシミテ王国", Code: "JO"},
	{Name: "Indonésia", Code: "ID"},
	{Name: "Мавритания", Code: "MR"},
	{Name: "澳门", Code: "MO"},
	{Name: "阿曼", Code: "OM"},
	{Name: "Mongolia", Code: "MN"},
	{Name: "Arabie saoudite", Code: "SA"},
	{Name: "Îles Marshall", Code: "MH"},
	{Name: "コスタリカ", Code: "CR"},
	{Name: "Ирак", Code: "IQ"},
	{Name: "Чад", Code: "TD"},
	{Name: "Никарагуа", Code: "NI"},
	{Name: "圣基茨和尼维斯", Code: "KN"},
	{Name: "Македония", Code: "MK"},
	{Name: "Croatia", Code: "HR"},
	{Name: "Malasia", Code: "MY"},
	{Name: "Myanmar [Birmania]", Code: "MM"},
	{Name: "Hongrie", Code: "HU"},
	{Name: "バヌアツ共和国", Code: "VU"},
	{Name: "パナマ", Code: "PA"},
	{Name: "Tailândia", Code: "TH"},
	{Name: "Сьерра-Леоне", Code: "SL"},
	{Name: "法罗群岛", Code: "FO"},
	{Name: "エクアドル共和国", Code: "EC"},
	{Name: "チリ共和国", Code: "CL"},
	{Name: "马提尼克群岛", Code: "MQ"},
	{Name: "Georgien", Code: "GE"},
	{Name: "Heard Island and McDonald Islands", Code: "HM"},
	{Name: "Território Britânico do Oceano Índico", Code: "IO"},
	{Name: "Мьянма", Code: "MM"},
	{Name: "Остров Рождества", Code: "CX"},
	{Name: "塔吉克斯坦", Code: "TJ"},
	{Name: "日本", Code: "JP"},
	{Name: "Багамы", Code: "BS"},
	{Name: "德国", Code: "DE"},
	{Name: "Chad", Code: "TD"},
	{Name: "ルーマニア", Code: "RO"},
	{Name: "マン島", Code: "IM"},
	{Name: "Питкэрн", Code: "PN"},
	{Name: "阿富汗", Code: "AF"},
	{Name: "密克罗尼西亚", Code: "FM"},
	{Name: "Israel", Code: "IL"},
	{Name: "Islas Feroe", Code: "FO"},
	{Name: "Bosnia-Herzegovina", Code: "BA"},
	{Name: "ケニア共和国", Code: "KE"},
	{Name: "ガーンジー", Code: "GG"},
	{Name: "Congo-Kinshasa", Code: "CD"},
	{Name: "圣马丁岛", Code: "SX"},
	{Name: "Deutschland", Code: "DE"},
	{Name: "U.S. Virgin Islands", Code: "VI"},
	{Name: "Liban", Code: "LB"},
	{Name: "ジャマイカ", Code: "JM"},
	{Name: "Новая Каледония", Code: "NC"},
	{Name: "Malawi", Code: "MW"},
	{Name: "Tuvalu", Code: "TV"},
	{Name: "Etiópia", Code: "ET"},
	{Name: "Sudão", Code: "SD"},
	{Name: "Самоа", Code: "WS"},
	{Name: "阿拉伯利比亚民众国", Code: "LY"},
	{Name: "阿鲁巴", Code: "AW"},
	{Name: "Hong Kong", Code: "HK"},
	{Name: "Ilhas Virgens Britânicas", Code: "VG"},
	{Name: "Франция", Code: "FR"},
	{Name: "Южная Джорджия и Южные Сандвичевы Острова", Code: "GS"},
	{Name: "Réunion", Code: "RE"},
	{Name: "Samoa", Code: "WS"},
	{Name: "Christmas Island", Code: "CX"},
	{Name: "Germany", Code: "DE"},
	{Name: "Islas Marianas del Norte", Code: "MP"},
	{Name: "République tchèque", Code: "CZ"},
	{Name: "Болгария", Code: "BG"},
	{Name: "库拉索", Code: "CW"},
	{Name: "越南", Code: "VN"},
	{Name: "Paraguay", Code: "PY"},
	{Name: "Zambia", Code: "ZM"},
	{Name: "Cabo Verde", Code: "CV"},
	{Name: "South Georgia and the South Sandwich Islands", Code: "GS"},
	{Name: "Myanmar", Code: "MM"},
	{Name: "Tanzânia", Code: "TZ"},
	{Name: "Молдова", Code: "MD"},
	{Name: "波斯尼亚和黑山共和国", Code: "BA"},
	{Name: "Amerikanisch-Samoa", Code: "AS"},
	{Name: "Antigua and Barbuda", Code: "AG"},
	{Name: "Kirguistán", Code: "KG"},
	{Name: "Pologne", Code: "PL"},
	{Name: "Ирландия", Code: "IE"},
	{Name: "不丹", Code: "BT"},
	{Name: "スバールバル諸島・ヤンマイエン島", Code: "SJ"},
	{Name: "Somalia", Code: "SO"},
	{Name: "Åland", Code: "AX"},
	{Name: "Saint Lucia", Code: "LC"},
	{Name: "Islas Salomón", Code: "SB"},
	{Name: "Panamá", Code: "PA"},
	{Name: "Sainte-Hélène", Code: "SH"},
	{Name: "アルバニア共和国", Code: "AL"},
	{Name: "斯威士兰", Code: "SZ"},
	{Name: "危地马拉", Code: "GT"},
	{Name: "开曼群岛", Code: "KY"},
	{Name: "Sao Tomé und Principe", Code: "ST"},
	{Name: "Uzbekistán", Code: "UZ"},
	{Name: "Canadá", Code: "CA"},
	{Name: "Saara Ocidental", Code: "EH"},
	{Name: "Eslovênia", Code: "SI"},
	{Name: "Тайланд", Code: "TH"},
	{Name: "Маршалловы о-ва", Code: "MH"},
	{Name: "Kongo (Republik Kongo)", Code: "CG"},
	{Name: "Mexico", Code: "MX"},
	{Name: "Ilhas Seychelles", Code: "SC"},
	{Name: "Suécia", Code: "SE"},
	{Name: "Nova Zelândia", Code: "NZ"},
	{Name: "Швеция", Code: "SE"},
	{Name: "Suisse", Code: "CH"},
	{Name: "ブルガリア共和国", Code: "BG"},
	{Name: "仏領極南諸島", Code: "TF"},
	{Name: "Ucrânia", Code: "UA"},
	{Name: "Марокко", Code: "MA"},
	{Name: "Чили", Code: "CL"},
	{Name: "巴林", Code: "BH"},
	{Name: "セネガル共和国", Code: "SN"},
	{Name: "Kapverden", Code: "CV"},
	{Name: "Papua New Guinea", Code: "PG"},
	{Name: "Côte d'Ivoire", Code: "CI"},
	{Name: "Algérie", Code: "DZ"},
	{Name: "Andorre", Code: "AD"},
	{Name: "République Dominicaine", Code: "DO"},
	{Name: "レバノン共和国", Code: "LB"},
	{Name: "ニジェール共和国", Code: "NE"},
	{Name: "Черногория", Code: "ME"},
	{Name: "冈比亚", Code: "GM"},
	{Name: "斯瓦尔巴特和扬马延", Code: "SJ"},
	{Name: "Usbekistan", Code: "UZ"},
	{Name: "Kosovo", Code: "XK"},
	{Name: "イエメン共和国", Code: "YE"},
	{Name: "スウェーデン王国", Code: "SE"},
	{Name: "英領インド洋地域", Code: "IO"},
	{Name: "印度尼西亚", Code: "ID"},
	{Name: "圣座（梵蒂冈）", Code: "VA"},
	{Name: "Trinidad und Tobago", Code: "TT"},
	{Name: "Pérou", Code: "PE"},
	{Name: "チュニジア共和国", Code: "TN"},
	{Name: "Libéria", Code: "LR"},
	{Name: "马尔代夫", Code: "MV"},
	{Name: "多哥", Code: "TG"},
	{Name: "突尼斯", Code: "TN"},
	{Name: "安道尔", Code: "AD"},
	{Name: "乌拉圭", Code: "UY"},
	{Name: "皮特凯恩群岛", Code: "PN"},
	{Name: "厄瓜多尔", Code: "EC"},
	{Name: "Palau", Code: "PW"},
	{Name: "Tunesien", Code: "TN"},
	{Name: "コンゴ共和国", Code: "CG"},
	{Name: "Líbia Árabe Jamahiriya", Code: "LY"},
	{Name: "Cingapura", Code: "SG"},
	{Name: "Замбия", Code: "ZM"},
	{Name: "Эстония", Code: "EE"},
	{Name: "Tokelau", Code: "TK"},
	{Name: "Yibuti", Code: "DJ"},
	{Name: "Brunéi", Code: "BN"},
	{Name: "Marruecos", Code: "MA"},
	{Name: "阿塞拜疆", Code: "AZ"},
	{Name: "阿尔巴尼亚", Code: "AL"},
	{Name: "朝鲜民主共和国", Code: "KP"},
	{Name: "Nordkorea", Code: "KP"},
	{Name: "Guernsey", Code: "GG"},
	{Name: "Svalbard et Jan Mayen", Code: "SJ"},
	{Name: "シリア・アラブ共和国", Code: "SY"},
	{Name: "バルバドス", Code: "BB"},
	{Name: "Vietnã", Code: "VN"},
	{Name: "Намибия", Code: "NA"},
	{Name: "圣文森特和格林纳丁斯", Code: "VC"},
	{Name: "缅甸", Code: "MM"},
	{Name: "Norwegen", Code: "NO"},
	{Name: "British Indian Ocean Territory", Code: "IO"},
	{Name: "Moldavie", Code: "MD"},
	{Name: "ポルトガル共和国", Code: "PT"},
	{Name: "Rússia", Code: "RU"},
	{Name: "Аруба", Code: "AW"},
	{Name: "Французская Полинезия", Code: "PF"},
	{Name: "Grèce", Code: "GR"},
	{Name: "Irlande", Code: "IE"},
	{Name: "Монако", Code: "MC"},
	{Name: "Österreich", Code: "AT"},
	{Name: "Suriname", Code: "SR"},
	{Name: "Rwanda", Code: "RW"},
	{Name: "Isle of Man", Code: "IM"},
	{Name: "Territorios Palestinos", Code: "PS"},
	{Name: "埃塞俄比亚", Code: "ET"},
	{Name: "喀麦隆", Code: "CM"},
	{Name: "Lettland", Code: "LV"},
	{Name: "Sierra Leone", Code: "SL"},
	{Name: "Géorgie", Code: "GE"},
	{Name: "Бразилия", Code: "BR"},
	{Name: "USA", Code: "US"},
	{Name: "San Pedro y Miquelón", Code: "PM"},
	{Name: "San Cristóbal y Nieves", Code: "KN"},
	{Name: "アメリカ合衆国", Code: "US"},
	{Name: "佛得角", Code: "CV"},
	{Name: "Montenegro", Code: "ME"},
	{Name: "Comoros", Code: "KM"},
	{Name: "Irán", Code: "IR"},
	{Name: "モンゴル国", Code: "MN"},
	{Name: "フェロー諸島", Code: "FO"},
	{Name: "Испания", Code: "ES"},
	{Name: "Letonia", Code: "LV"},
	{Name: "Granada", Code: "GD"},
	{Name: "米領ヴァージン諸島", Code: "VI"},
	{Name: "帕劳", Code: "PW"},
	{Name: "澳大利亚", Code: "AU"},
	{Name: "法属圭亚那", Code: "GF"},
	{Name: "Indonesien", Code: "ID"},
	{Name: "Luxembourg", Code: "LU"},
	{Name: "パラグアイ共和国", Code: "PY"},
	{Name: "Namíbia", Code: "NA"},
	{Name: "索马里", Code: "SO"},
	{Name: "Суринам", Code: "SR"},
	{Name: "Russland", Code: "RU"},
	{Name: "Bahamas", Code: "BS"},
	{Name: "St. Barthélemy", Code: "BL"},
	{Name: "United Arab Emirates", Code: "AE"},
	{Name: "東ティモール共和国", Code: "TL"},
	{Name: "エルサルバドル", Code: "SV"},
	{Name: "Йемен", Code: "YE"},
	{Name: "莫桑比克", Code: "MZ"},
	{Name: "Palaos", Code: "PW"},
	{Name: "Islas Turcas y Caicos", Code: "TC"},
	{Name: "Áustria", Code: "AT"},
	{Name: "Казахстан", Code: "KZ"},
	{Name: "赞比亚", Code: "ZM"},
	{Name: "Ivory Coast", Code: "CI"},
	{Name: "Bahreïn", Code: "BH"},
	{Name: "ミクロネシア連邦", Code: "FM"},
	{Name: "Мозамбик", Code: "MZ"},
	{Name: "Тайвань", Code: "TW"},
	{Name: "马约特", Code: "YT"},
	{Name: "Mauritius", Code: "MU"},
	{Name: "Elfenbeinküste", Code: "CI"},
	{Name: "Turquie", Code: "TR"},
	{Name: "Belgique", Code: "BE"},
	{Name: "Palästinensische Autonomiegebiete", Code: "PS"},
	{Name: "Guinée équatoriale", Code: "GQ"},
	{Name: "ベリーズ", Code: "BZ"},
	{Name: "Антарктида", Code: "AQ"},
	{Name: "Biélorussie", Code: "BY"},
	{Name: "República Centro-Africana", Code: "CF"},
	{Name: "也门", Code: "YE"},
	{Name: "Trinidad and Tobago", Code: "TT"},
	{Name: "Papúa-Nueva Guinea", Code: "PG"},
	{Name: "ギリシャ共和国", Code: "GR"},
	{Name: "ベネズエラ共和国", Code: "VE"},
	{Name: "仏領ポリネシア", Code: "PF"},
	{Name: "Mianmar [Birmânia]", Code: "MM"},
	{Name: "Ilha Norfolk", Code: "NF"},
	{Name: "瑞士", Code: "CH"},
	{Name: "卢森堡", Code: "LU"},
	{Name: "Сан-Марино", Code: "SM"},
	{Name: "Macedonia", Code: "MK"},
	{Name: "南ジョージア島・南サンドイッチ諸島", Code: "GS"},
	{Name: "Austrália", Code: "AU"},
	{Name: "Serra Leoa", Code: "SL"},
	{Name: "Santa Lúcia", Code: "LC"},
	{Name: "Сомали", Code: "SO"},
	{Name: "Малайзия", Code: "MY"},
	{Name: "乍得", Code: "TD"},
	{Name: "Vietnam", Code: "VN"},
	{Name: "イラク共和国", Code: "IQ"},
	{Name: "イタリア共和国", Code: "IT"},
	{Name: "フランス共和国", Code: "FR"},
	{Name: "Guiana Francesa", Code: "GF"},
	{Name: "Израиль", Code: "IL"},
	{Name: "特立尼达和多巴哥", Code: "TT"},
	{Name: "Malásia", Code: "MY"},
	{Name: "Rusia", Code: "RU"},
	{Name: "Nueva Caledonia", Code: "NC"},
	{Name: "Slovaquie", Code: "SK"},
	{Name: "ミャンマー連邦", Code: "MM"},
	{Name: "オーストラリア", Code: "AU"},
	{Name: "マーシャル諸島共和国", Code: "MH"},
	{Name: "Tajiquistão", Code: "TJ"},
	{Name: "Япония", Code: "JP"},
	{Name: "波兰", Code: "PL"},
	{Name: "曼岛", Code: "IM"},
	{Name: "Falkland Islands", Code: "FK"},
	{Name: "Bután", Code: "BT"},
	{Name: "汤加", Code: "TO"},
	{Name: "Slowakei (Slowakische Republik)", Code: "SK"},
	{Name: "Maurice", Code: "MU"},
	{Name: "カンボジア国", Code: "KH"},
	{Name: "キュラソー", Code: "CW"},
	{Name: "Polinésia Francesa", Code: "PF"},
	{Name: "Узбекистан", Code: "UZ"},
	{Name: "Уругвай", Code: "UY"},
	{Name: "Кокосовые о-ва", Code: "CC"},
	{Name: "Islas Cook", Code: "CK"},
	{Name: "Haïti", Code: "HT"},
	{Name: "スロバキア (スロバキア共和国)", Code: "SK"},
	{Name: "トーゴ共和国", Code: "TG"},
	{Name: "仏領ギアナ", Code: "GF"},
	{Name: "Finlândia", Code: "FI"},
	{Name: "Кипр", Code: "CY"},
	{Name: "Мали", Code: "ML"},
	{Name: "利比里亚", Code: "LR"},
	{Name: "French Southern Territories", Code: "TF"},
	{Name: "Nouvelle-Zélande", Code: "NZ"},
	{Name: "社会主義人民リビア・アラブ国", Code: "LY"},
	{Name: "南スーダン", Code: "SS"},
	{Name: "プエルトリコ", Code: "PR"},
	{Name: "República de Moçambique", Code: "MZ"},
	{Name: "Venezuela", Code: "VE"},
	{Name: "Algeria", Code: "DZ"},
	{Name: "Dominique", Code: "DM"},
	{Name: "Uruguay", Code: "UY"},
	{Name: "St. Vincent und die Grenadinen", Code: "VC"},
	{Name: "Sweden", Code: "SE"},
	{Name: "Ilha Heard e Ilhas McDonald", Code: "HM"},
	{Name: "Мальдивские о-ва", Code: "MV"},
	{Name: "Великобритания", Code: "GB"},
	{Name: "Пуэрто-Рико", Code: "PR"},
	{Name: "Ангилья", Code: "AI"},
	{Name: "Serbia", Code: "RS"},
	{Name: "Federated States of Micronesia", Code: "FM"},
	{Name: "Italy", Code: "IT"},
	{Name: "Malaui", Code: "MW"},
	{Name: "ウクライナ共和国", Code: "UA"},
	{Name: "Реюньон", Code: "RE"},
	{Name: "Французские Южные Территории", Code: "TF"},
	{Name: "英属印度洋领地", Code: "IO"},
	{Name: "Sud-Soudan", Code: "SS"},
	{Name: "英領ヴァージン諸島", Code: "VG"},
	{Name: "Irã", Code: "IR"},
	{Name: "Lesoto", Code: "LS"},
	{Name: "Гонконг", Code: "HK"},
	{Name: "Кюрасао", Code: "CW"},
	{Name: "República Dominicana", Code: "DO"},
	{Name: "Ливия", Code: "LY"},
	{Name: "印度", Code: "IN"},
	{Name: "格陵兰", Code: "GL"},
	{Name: "Aruba", Code: "AW"},
	{Name: "Ireland", Code: "IE"},
	{Name: "トルクメニスタン", Code: "TM"},
	{Name: "バミューダ諸島", Code: "BM"},
	{Name: "Sudão do Sul", Code: "SS"},
	{Name: "Буркина Фасо", Code: "BF"},
	{Name: "Гренландия", Code: "GL"},
	{Name: "罗马尼亚", Code: "RO"},
	{Name: "Französisch-Guayana", Code: "GF"},
	{Name: "Antigua und Barbuda", Code: "AG"},
	{Name: "Tunisie", Code: "TN"},
	{Name: "Quiribati", Code: "KI"},
	{Name: "Бенин", Code: "BJ"},
	{Name: "Австрия", Code: "AT"},
	{Name: "Острова Зеленого Мыса", Code: "CV"},
	{Name: "纳米比亚", Code: "NA"},
	{Name: "Bonaire", Code: "BQ"},
	{Name: "Vatican", Code: "VA"},
	{Name: "Mexique", Code: "MX"},
	{Name: "中華民国", Code: "TW"},
	{Name: "キューバ共和国", Code: "CU"},
	{Name: "Румыния", Code: "RO"},
	{Name: "马耳他", Code: "MT"},
	{Name: "Litauen", Code: "LT"},
	{Name: "Guyane", Code: "GF"},
	{Name: "Nova Caledônia", Code: "NC"},
	{Name: "Таджикистан", Code: "TJ"},
	{Name: "Malta", Code: "MT"},
	{Name: "Japón", Code: "JP"},
	{Name: "Zâmbia", Code: "ZM"},
	{Name: "Albânia", Code: "AL"},
	{Name: "布维特岛", Code: "BV"},
	{Name: "Saudi-Arabien", Code: "SA"},
	{Name: "São Tomé and Príncipe", Code: "ST"},
	{Name: "Níger", Code: "NE"},
	{Name: "Trinidad y Tobago", Code: "TT"},
	{Name: "コンゴ民主共和国", Code: "CD"},
	{Name: "グルジア共和国", Code: "GE"},
	{Name: "Кыргызстан", Code: "KG"},
	{Name: "Simbabwe", Code: "ZW"},
	{Name: "Britisches Territorium im Indischen Ozean", Code: "IO"},
	{Name: "Slovenia", Code: "SI"},
	{Name: "Taiwán", Code: "TW"},
	{Name: "カメルーン共和国", Code: "CM"},
	{Name: "Азербайджан", Code: "AZ"},
	{Name: "Украина", Code: "UA"},
	{Name: "ニカラグア共和国", Code: "NI"},
	{Name: "Polen", Code: "PL"},
	{Name: "Brunei", Code: "BN"},
	{Name: "Luxemburg", Code: "LU"},
	{Name: "Tajikistan", Code: "TJ"},
	{Name: "France", Code: "FR"},
	{Name: "香港", Code: "HK"},
	{Name: "赤道ギニア共和国", Code: "GQ"},
	{Name: "Moldova, República de", Code: "MD"},
	{Name: "博茨瓦纳", Code: "BW"},
	{Name: "斯洛文尼亚", Code: "SI"},
	{Name: "Bahrain", Code: "BH"},
	{Name: "Hungría", Code: "HU"},
	{Name: "パプア・ニューギニア", Code: "PG"},
	{Name: "Letônia", Code: "LV"},
	{Name: "布隆迪", Code: "BI"},
	{Name: "留尼汪", Code: "RE"},
	{Name: "洪都拉斯", Code: "HN"},
	{Name: "Switzerland", Code: "CH"},
	{Name: "Mónaco", Code: "MC"},
	{Name: "Tchéquia", Code: "CZ"},
	{Name: "Antígua e Barbuda", Code: "AG"},
	{Name: "乌干达", Code: "UG"},
	{Name: "奥兰群岛", Code: "AX"},
	{Name: "所罗门群岛", Code: "SB"},
	{Name: "Burkina Faso", Code: "BF"},
	{Name: "Líbano", Code: "LB"},
	{Name: "República da Guiné-Bissau", Code: "GW"},
	{Name: "Сейшельские о-ва", Code: "SC"},
	{Name: "扎伊尔", Code: "CD"},
	{Name: "Mongólia", Code: "MN"},
	{Name: "Griechenland", Code: "GR"},
	{Name: "Gibraltar", Code: "GI"},
	{Name: "Bulgaria", Code: "BG"},
	{Name: "Porto Rico", Code: "PR"},
	{Name: "イラン・イスラム共和国", Code: "IR"},
	{Name: "クロアチア共和国", Code: "HR"},
	{Name: "Hungria", Code: "HU"},
	{Name: "Сан-Томе и Принсипе", Code: "ST"},
	{Name: "柬埔寨", Code: "KH"},
	{Name: "巴哈马", Code: "BS"},
	{Name: "美属萨摩亚", Code: "AS"},
	{Name: "Yemen", Code: "YE"},
	{Name: "Slovakia", Code: "SK"},
	{Name: "マラウイ共和国", Code: "MW"},
	{Name: "吉尔吉克斯坦", Code: "KG"},
	{Name: "塞内加尔", Code: "SN"},
	{Name: "États-Unis", Code: "US"},
	{Name: "マルティニーク島", Code: "MQ"},
	{Name: "Иран", Code: "IR"},
	{Name: "爱沙尼亚", Code: "EE"},
	{Name: "南非", Code: "ZA"},
	{Name: "塞拉利昂", Code: "SL"},
	{Name: "美国", Code: "US"},
	{Name: "Slovénie", Code: "SI"},
	{Name: "Mongolei", Code: "MN"},
	{Name: "Fiyi", Code: "FJ"},
	{Name: "Santo Tomé y Príncipe", Code: "ST"},
	{Name: "Eslovenia", Code: "SI"},
	{Name: "Chypre", Code: "CY"},
	{Name: "Centrafrique", Code: "CF"},
	{Name: "Cambodge", Code: "KH"},
	{Name: "クウェート", Code: "KW"},
	{Name: "マリ共和国", Code: "ML"},
	{Name: "Острова Тёркс и Кайкос", Code: "TC"},
	{Name: "津巴布韦", Code: "ZW"},
	{Name: "委内瑞拉", Code: "VE"},
	{Name: "安提瓜和巴布达", Code: "AG"},
	{Name: "エチオピア", Code: "ET"},
	{Name: "ハード島・マクドナルド諸島", Code: "HM"},
	{Name: "リヒテンシュタイン公国", Code: "LI"},
	{Name: "セントビンセント・グレナディーン諸島", Code: "VC"},
	{Name: "Руанда", Code: "RW"},
	{Name: "Люксембург", Code: "LU"},
	{Name: "Филиппины", Code: "PH"},
	{Name: "Madagaskar", Code: "MG"},
	{Name: "", Code: ""},
	{Name: "Finlandia", Code: "FI"},
	{Name: "Territoire palestinien", Code: "PS"},
	{Name: "ハンガリー共和国", Code: "HU"},
	{Name: "ココス[キーリング]諸島", Code: "CC"},
	{Name: "Косово", Code: "XK"},
	{Name: "Guiana", Code: "GY"},
	{Name: "Heard- und McDonald-Inseln", Code: "HM"},
	{Name: "Dominican Republic", Code: "DO"},
	{Name: "Tadjikistan", Code: "TJ"},
	{Name: "Îles Vierges", Code: "VG"},
	{Name: "Djibuti", Code: "DJ"},
	{Name: "Japão", Code: "JP"},
	{Name: "Svalbard e Jan Mayen", Code: "SJ"},
	{Name: "Норвегия", Code: "NO"},
	{Name: "圣巴泰勒米", Code: "BL"},
	{Name: "Чешская Республика", Code: "CZ"},
	{Name: "Namibia", Code: "NA"},
	{Name: "Sint Maarten", Code: "SX"},
	{Name: "Turkménistan", Code: "TM"},
	{Name: "Arménie", Code: "AM"},
	{Name: "Australie", Code: "AU"},
	{Name: "中央アフリカ共和国", Code: "CF"},
	{Name: "カナダ", Code: "CA"},
	{Name: "伊拉克", Code: "IQ"},
	{Name: "Französisch-Polynesien", Code: "PF"},
	{Name: "Moldavia", Code: "MD"},
	{Name: "Islas Pitcairn", Code: "PN"},
	{Name: "カザフスタン共和国", Code: "KZ"},
	{Name: "アンドラ", Code: "AD"},
	{Name: "Nicarágua", Code: "NI"},
	{Name: "Ватикан", Code: "VA"},
	{Name: "Îles Åland", Code: "AX"},
	{Name: "シント・マールテン", Code: "SX"},
	{Name: "Германия", Code: "DE"},
	{Name: "Äthiopien", Code: "ET"},
	{Name: "Nigeria", Code: "NG"},
	{Name: "Spanien", Code: "ES"},
	{Name: "Turkey", Code: "TR"},
	{Name: "Brazil", Code: "BR"},
	{Name: "Territoire britannique de l'océan Indien", Code: "IO"},
	{Name: "Saint Pierre e Miquelon", Code: "PM"},
	{Name: "比利时", Code: "BE"},
	{Name: "Serbien", Code: "RS"},
	{Name: "Tunisia", Code: "TN"},
	{Name: "Islandia", Code: "IS"},
	{Name: "Romênia", Code: "RO"},
	{Name: "Ilhas Turks e Caicos", Code: "TC"},
	{Name: "Коста-Рика", Code: "CR"},
	{Name: "圣诞岛", Code: "CX"},
	{Name: "St. Helena", Code: "SH"},
	{Name: "Curaçao", Code: "CW"},
	{Name: "スイス連邦", Code: "CH"},
	{Name: "Bolívia", Code: "BO"},
	{Name: "黎巴嫩", Code: "LB"},
	{Name: "Alandinseln", Code: "AX"},
	{Name: "Pakistan", Code: "PK"},
	{Name: "El Salvador", Code: "SV"},
	{Name: "Bulgária", Code: "BG"},
	{Name: "Джибути", Code: "DJ"},
	{Name: "土库曼斯坦", Code: "TM"},
	{Name: "叙利亚", Code: "SY"},
	{Name: "智利", Code: "CL"},
	{Name: "French Guiana", Code: "GF"},
	{Name: "Polonia", Code: "PL"},
	{Name: "トルコ共和国", Code: "TR"},
	{Name: "Бурунди", Code: "BI"},
	{Name: "Коморские о-ва", Code: "KM"},
	{Name: "Сенегал", Code: "SN"},
	{Name: "海地", Code: "HT"},
	{Name: "Finland", Code: "FI"},
	{Name: "Samoa Americana", Code: "AS"},
	{Name: "Кения", Code: "KE"},
	{Name: "Камбоджа", Code: "KH"},
	{Name: "Кирибати", Code: "KI"},
	{Name: "毛里塔尼亚", Code: "MR"},
	{Name: "阿拉伯联合酋长国", Code: "AE"},
	{Name: "Ecuador", Code: "EC"},
	{Name: "Saint Pierre and Miquelon", Code: "PM"},
	{Name: "Zimbawe", Code: "ZW"},
	{Name: "Isla Bouvet", Code: "BV"},
	{Name: "Islande", Code: "IS"},
	{Name: "Vaticano", Code: "VA"},
	{Name: "Бонайре, Синт-Эстатиус и Саба", Code: "BQ"},
	{Name: "立陶宛", Code: "LT"},
	{Name: "阿尔及利亚", Code: "DZ"},
	{Name: "美属维京群岛", Code: "VI"},
	{Name: "Kanada", Code: "CA"},
	{Name: "República Centroafricana", Code: "CF"},
	{Name: "Suiza", Code: "CH"},
	{Name: "Syrie", Code: "SY"},
	{Name: "モザンビーク共和国", Code: "MZ"},
	{Name: "São Cristóvão e Névis", Code: "KN"},
	{Name: "前南斯拉夫马其顿共和国", Code: "MK"},
	{Name: "American Samoa", Code: "AS"},
	{Name: "エジプト・アラブ共和国", Code: "EG"},
	{Name: "モーリタニア・イスラム共和国", Code: "MR"},
	{Name: "イギリス", Code: "GB"},
	{Name: "Maurício", Code: "MU"},
	{Name: "アゼルバイジャン共和国", Code: "AZ"},
	{Name: "タンザニア連合共和国", Code: "TZ"},
	{Name: "Cook Islands", Code: "CK"},
	{Name: "Denmark", Code: "DK"},
	{Name: "Netherlands", Code: "NL"},
	{Name: "Lituania", Code: "LT"},
	{Name: "Lettonie", Code: "LV"},
	{Name: "ポーランド共和国", Code: "PL"},
	{Name: "フォークランド諸島", Code: "FK"},
	{Name: "Französische Süd- und Antarktisgebiete", Code: "TF"},
	{Name: "Norfolkinsel", Code: "NF"},
	{Name: "Dom. Republik", Code: "DO"},
	{Name: "クック諸島", Code: "CK"},
	{Name: "Espanha", Code: "ES"},
	{Name: "Argélia", Code: "DZ"},
	{Name: "Tschad", Code: "TD"},
	{Name: "Portugal", Code: "PT"},
	{Name: "Groenland", Code: "GL"},
	{Name: "エストニア共和国", Code: "EE"},
	{Name: "中国", Code: "CN"},
	{Name: "サントメ・プリンシペ", Code: "ST"},
	{Name: "ピトケアン島", Code: "PN"},
	{Name: "Бельгия", Code: "BE"},
	{Name: "San Marino", Code: "SM"},
	{Name: "Îles Cook", Code: "CK"},
	{Name: "Salvador", Code: "SV"},
	{Name: "Ilhas Virgens dos EUA", Code: "VI"},
	{Name: "Монголия", Code: "MN"},
	{Name: "特克斯和凯科斯群岛", Code: "TC"},
	{Name: "Noruega", Code: "NO"},
	{Name: "Costa de Marfil", Code: "CI"},
	{Name: "Antarctique", Code: "AQ"},
	{Name: "Словакия", Code: "SK"},
	{Name: "摩洛哥", Code: "MA"},
	{Name: "アンギラ", Code: "AI"},
	{Name: "セントルシア", Code: "LC"},
	{Name: "Аланды", Code: "AX"},
	{Name: "Türkei", Code: "TR"},
	{Name: "Kamerun", Code: "CM"},
	{Name: "Tanzania", Code: "TZ"},
	{Name: "Northern Mariana Islands", Code: "MP"},
	{Name: "ウガンダ共和国", Code: "UG"},
	{Name: "ジブラルタル", Code: "GI"},
	{Name: "Azerbaijão", Code: "AZ"},
	{Name: "Kirgistan", Code: "KG"},
	{Name: "Kirghizistan", Code: "KG"},
	{Name: "Papua-Nova Guiné", Code: "PG"},
	{Name: "Габон", Code: "GA"},
	{Name: "纽埃", Code: "NU"},
	{Name: "Nepal", Code: "NP"},
	{Name: "Saint Vincent and the Grenadines", Code: "VC"},
	{Name: "Trinidad et Tobago", Code: "TT"},
	{Name: "パキスタン・イスラム共和国", Code: "PK"},
	{Name: "Гана", Code: "GH"},
	{Name: "Italien", Code: "IT"},
	{Name: "Мальта", Code: "MT"},
	{Name: "保加利亚", Code: "BG"},
	{Name: "马绍尔群岛", Code: "MH"},
	{Name: "以色列", Code: "IL"},
	{Name: "Vereinigte Arabische Emirate", Code: "AE"},
	{Name: "Hongkong", Code: "HK"},
	{Name: "Australien", Code: "AU"},
	{Name: "Grenada", Code: "GD"},
	{Name: "Guatemala", Code: "GT"},
	{Name: "アルジェリア民主人民共和国", Code: "DZ"},
	{Name: "アンティグア・バーブーダ", Code: "AG"},
	{Name: "Saint-Barthélemy", Code: "BL"},
	{Name: "Belice", Code: "BZ"},
	{Name: "Suède", Code: "SE"},
	{Name: "Saint-Marin", Code: "SM"},
	{Name: "ノーフォーク島", Code: "NF"},
	{Name: "新加坡", Code: "SG"},
	{Name: "Mikronesien", Code: "FM"},
	{Name: "Sudán del Sur", Code: "SS"},
	{Name: "Îles Cocos", Code: "CC"},
	{Name: "Camboja", Code: "KH"},
	{Name: "Латвия", Code: "LV"},
	{Name: "Палау", Code: "PW"},
	{Name: "Парагвай", Code: "PY"},
	{Name: "Gabun", Code: "GA"},
	{Name: "Färöer-Inseln", Code: "FO"},
	{Name: "Ethiopia", Code: "ET"},
	{Name: "Bonaire, Saint-Eustache et Saba", Code: "BQ"},
	{Name: "Ботсвана", Code: "BW"},
	{Name: "Пакистан", Code: "PK"},
	{Name: "Лихтенштейн", Code: "LI"},
	{Name: "トリニダード・トバゴ共和国", Code: "TT"},
	{Name: "Танзания", Code: "TZ"},
	{Name: "Южный Судан", Code: "SS"},
	{Name: "Ниуе", Code: "NU"},
	{Name: "博奈尔岛、圣尤斯达蒂斯和萨巴", Code: "BQ"},
	{Name: "Congo", Code: "CG"},
	{Name: "Vénézuéla", Code: "VE"},
	{Name: "Saint-Martin", Code: "SX"},
	{Name: "サン・バルテルミー", Code: "BL"},
	{Name: "Венгрия", Code: "HU"},
	{Name: "Гибралтар", Code: "GI"},
	{Name: "挪威", Code: "NO"},
	{Name: "Cookinseln", Code: "CK"},
	{Name: "Pitcairn", Code: "PN"},
	{Name: "Irlanda", Code: "IE"},
	{Name: "Pays-Bas", Code: "NL"},
	{Name: "パレスチナ", Code: "PS"},
	{Name: "Lituânia", Code: "LT"},
	{Name: "Geórgia do Sul e Ilhas Sandwich do Sul", Code: "GS"},
	{Name: "黑山共和国", Code: "ME"},
	{Name: "Papua-Neuguinea", Code: "PG"},
	{Name: "Royaume-Uni", Code: "GB"},
	{Name: "ウルグアイ共和国", Code: "UY"},
	{Name: "Ilhas Natal", Code: "CX"},
	{Name: "Майотта", Code: "YT"},
	{Name: "塞浦路斯", Code: "CY"},
	{Name: "冰岛", Code: "IS"},
	{Name: "瓜德罗普岛", Code: "GP"},
	{Name: "Seychelles", Code: "SC"},
	{Name: "Cameroon", Code: "CM"},
	{Name: "Croacia", Code: "HR"},
	{Name: "Antártida", Code: "AQ"},
	{Name: "リベリア共和国", Code: "LR"},
	{Name: "África do Sul", Code: "ZA"},
	{Name: "Ilhas Malvinas", Code: "FK"},
	{Name: "Bélgica", Code: "BE"},
	{Name: "Islas Vírgenes", Code: "VG"},
	{Name: "Espagne", Code: "ES"},
	{Name: "Îles mineures éloignées des États-Unis", Code: "UM"},
	{Name: "Сербия", Code: "RS"},
	{Name: "Словения", Code: "SI"},
	{Name: "Уоллис и Футуна", Code: "WF"},
	{Name: "Hashemite Kingdom of Jordan", Code: "JO"},
	{Name: "Thaïlande", Code: "TH"},
	{Name: "ドミニカ共和国", Code: "DO"},
	{Name: "Эритрея", Code: "ER"},
	{Name: "希腊", Code: "GR"},
	{Name: "Mayotte", Code: "YT"},
	{Name: "泰国", Code: "TH"},
	{Name: "尼日尔", Code: "NE"},
	{Name: "加纳", Code: "GH"},
	{Name: "Neuseeland", Code: "NZ"},
	{Name: "French Polynesia", Code: "PF"},
	{Name: "Singapour", Code: "SG"},
	{Name: "ジブチ", Code: "DJ"},
	{Name: "Coreia do Sul", Code: "KR"},
	{Name: "Вануату", Code: "VU"},
	{Name: "Остров Норфолк", Code: "NF"},
	{Name: "丹麦", Code: "DK"},
	{Name: "Albanien", Code: "AL"},
	{Name: "New Caledonia", Code: "NC"},
	{Name: "Surinam", Code: "SR"},
	{Name: "Chade", Code: "TD"},
	{Name: "Lichtenstein", Code: "LI"},
	{Name: "Сент-Винсент и Гренадины", Code: "VC"},
	{Name: "菲律宾", Code: "PH"},
	{Name: "Mauretanien", Code: "MR"},
	{Name: "Belgien", Code: "BE"},
	{Name: "ネパール王国", Code: "NP"},
	{Name: "サンマリノ共和国", Code: "SM"},
	{Name: "Coreia do Norte", Code: "KP"},
	{Name: "埃及", Code: "EG"},
	{Name: "Swasiland", Code: "SZ"},
	{Name: "Suecia", Code: "SE"},
	{Name: "Corea del Norte", Code: "KP"},
	{Name: "Estonie", Code: "EE"},
	{Name: "バーレーン", Code: "BH"},
	{Name: "南乔治亚岛和南桑威齐群岛", Code: "GS"},
	{Name: "Solomon-Inseln", Code: "SB"},
	{Name: "Afganistán", Code: "AF"},
	{Name: "Taïwan", Code: "TW"},
	{Name: "タークス諸島・カイコス諸島", Code: "TC"},
	{Name: "格鲁吉亚", Code: "GE"},
	{Name: "东帝汶", Code: "TL"},
	{Name: "俄罗斯", Code: "RU"},
	{Name: "Sambia", Code: "ZM"},
	{Name: "Barbados", Code: "BB"},
	{Name: "Barbade", Code: "BB"},
	{Name: "デンマーク王国", Code: "DK"},
	{Name: "オランダ王国", Code: "NL"},
	{Name: "Китай", Code: "CN"},
	{Name: "Монсеррат", Code: "MS"},
	{Name: "克罗地亚", Code: "HR"},
	{Name: "セルビア", Code: "RS"},
	{Name: "Bouvetinsel", Code: "BV"},
	{Name: "Mexiko", Code: "MX"},
	{Name: "Mozambique", Code: "MZ"},
	{Name: "Singapore", Code: "SG"},
	{Name: "Fidji", Code: "FJ"},
	{Name: "Géorgie du Sud-et-les îles Sandwich du Sud", Code: "GS"},
	{Name: "ザンビア共和国", Code: "ZM"},
	{Name: "マルタ島", Code: "MT"},
	{Name: "Науру", Code: "NR"},
	{Name: "Сен-Пьер и Микелон", Code: "PM"},
	{Name: "Сент-Киттс и Невис", Code: "KN"},
	{Name: "Bulgarien", Code: "BG"},
	{Name: "España", Code: "ES"},
	{Name: "Holanda", Code: "NL"},
	{Name: "Guadalupe", Code: "GP"},
	{Name: "Maroc", Code: "MA"},
	{Name: "瑞典", Code: "SE"},
	{Name: "Reunião", Code: "RE"},
	{Name: "China", Code: "CN"},
	{Name: "Kokosinseln", Code: "CC"},
	{Name: "Antarktis", Code: "AQ"},
	{Name: "Île Christmas", Code: "CX"},
	{Name: "Autriche", Code: "AT"},
	{Name: "インド", Code: "IN"},
	{Name: "フィリピン共和国", Code: "PH"},
	{Name: "Каймановы Острова", Code: "KY"},
	{Name: "匈牙利", Code: "HU"},
	{Name: "Острова Кука", Code: "CK"},
	{Name: "Соломонские острова", Code: "SB"},
	{Name: "南极洲", Code: "AQ"},
	{Name: "Bhutan", Code: "BT"},
	{Name: "Belize", Code: "BZ"},
	{Name: "Guinea-Bissáu", Code: "GW"},
	{Name: "Bosnie-Herzégovine", Code: "BA"},
	{Name: "ベラルーシ共和国", Code: "BY"},
	{Name: "Восточный Тимор", Code: "TL"},
	{Name: "Северная Корея", Code: "KP"},
	{Name: "Südgeorgien und die Südlichen Sandwichinseln", Code: "GS"},
	{Name: "Albania", Code: "AL"},
	{Name: "Tanzanie", Code: "TZ"},
	{Name: "ボリビア共和国", Code: "BO"},
	{Name: "波多黎各", Code: "PR"},
	{Name: "Аргентина", Code: "AR"},
	{Name: "Argentinien", Code: "AR"},
	{Name: "Tonga", Code: "TO"},
	{Name: "Bouvet Island", Code: "BV"},
	{Name: "Reunión", Code: "RE"},
	{Name: "スリナム共和国", Code: "SR"},
	{Name: "Бангладеш", Code: "BD"},
	{Name: "Нидерланды", Code: "NL"},
	{Name: "乌兹别克斯坦", Code: "UZ"},
	{Name: "Dominica", Code: "DM"},
	{Name: "Micronesia", Code: "FM"},
	{Name: "アイスランド共和国", Code: "IS"},
	{Name: "塞尔维亚", Code: "RS"},
	{Name: "葡萄牙", Code: "PT"},
	{Name: "Ilhas Marshall", Code: "MH"},
	{Name: "Sudan", Code: "SD"},
	{Name: "Bahréin", Code: "BH"},
	{Name: "Camboya", Code: "KH"},
	{Name: "Isla de Man", Code: "IM"},
	{Name: "Groenlandia", Code: "GL"},
	{Name: "スリランカ民主社会主義共和国", Code: "LK"},
	{Name: "Quênia", Code: "KE"},
	{Name: "Микронезия", Code: "FM"},
	{Name: "Куба", Code: "CU"},
	{Name: "Антигуа и Барбуда", Code: "AG"},
	{Name: "巴西", Code: "BR"},
	{Name: "圣卢西亚", Code: "LC"},
	{Name: "Iran (Islamische Republik)", Code: "IR"},
	{Name: "Allemagne", Code: "DE"},
	{Name: "Eslováquia", Code: "SK"},
	{Name: "西撒哈拉", Code: "EH"},
	{Name: "Libanon", Code: "LB"},
	{Name: "RDC", Code: "CD"},
	{Name: "Guernesey", Code: "GG"},
	{Name: "モルジブ", Code: "MV"},
	{Name: "Tuwalu", Code: "TV"},
	{Name: "ブラジル連邦共和国", Code: "BR"},
	{Name: "Перу", Code: "PE"},
	{Name: "Колумбия", Code: "CO"},
	{Name: "Chipre", Code: "CY"},
	{Name: "Ouzbékistan", Code: "UZ"},
	{Name: "ペルー共和国", Code: "PE"},
	{Name: "米領サモア", Code: "AS"},
	{Name: "ОАЭ", Code: "AE"},
	{Name: "Швейцария", Code: "CH"},
	{Name: "Мартиника", Code: "MQ"},
	{Name: "St. Pierre und Miquelon", Code: "PM"},
	{Name: "Turks and Caicos Islands", Code: "TC"},
	{Name: "Pakistán", Code: "PK"},
	{Name: "Sahara Occidental", Code: "EH"},
	{Name: "Saint-Christophe-et-Niévès", Code: "KN"},
	{Name: "Armênia", Code: "AM"},
	{Name: "英国", Code: "GB"},
	{Name: "巴布亚新几内亚", Code: "PG"},
	{Name: "Tschechien", Code: "CZ"},
	{Name: "Yémen", Code: "YE"},
	{Name: "Cap-Vert", Code: "CV"},
	{Name: "バングラディッシュ人民共和国", Code: "BD"},
	{Name: "Турция", Code: "TR"},
	{Name: "Малави", Code: "MW"},
	{Name: "巴基斯坦", Code: "PK"},
	{Name: "尼日利亚", Code: "NG"},
	{Name: "马里", Code: "ML"},
	{Name: "Bósnia-Herzegóvina", Code: "BA"},
	{Name: "Niger", Code: "NE"},
	{Name: "Kazajstán", Code: "KZ"},
	{Name: "Eslovaquia", Code: "SK"},
	{Name: "カタール", Code: "QA"},
	{Name: "ブータン王国", Code: "BT"},
	{Name: "モンテネグロ", Code: "ME"},
	{Name: "Nigéria", Code: "NG"},
	{Name: "安圭拉", Code: "AI"},
	{Name: "Dschibuti", Code: "DJ"},
	{Name: "Anguilla", Code: "AI"},
	{Name: "Bulgarie", Code: "BG"},
	{Name: "Polynésie Française", Code: "PF"},
	{Name: "Micronésia", Code: "FM"},
	{Name: "Ilhas Marianas do Norte", Code: "MP"},
	{Name: "美国边远小岛", Code: "UM"},
	{Name: "Botswana", Code: "BW"},
	{Name: "Kazakhstan", Code: "KZ"},
	{Name: "Érythrée", Code: "ER"},
	{Name: "モーリシャス", Code: "MU"},
	{Name: "ギニアビサウ共和国", Code: "GW"},
	{Name: "Bosnien und Herzegowina", Code: "BA"},
	{Name: "Cyprus", Code: "CY"},
	{Name: "Myanmar [Burma]", Code: "MM"},
	{Name: "Egito", Code: "EG"},
	{Name: "玻利维亚", Code: "BO"},
	{Name: "加拿大", Code: "CA"},
	{Name: "Gabón", Code: "GA"},
	{Name: "Danemark", Code: "DK"},
	{Name: "Польша", Code: "PL"},
	{Name: "Hungary", Code: "HU"},
	{Name: "Equatorial Guinea", Code: "GQ"},
	{Name: "Croatie", Code: "HR"},
	{Name: "Австралия", Code: "AU"},
	{Name: "卢旺达", Code: "RW"},
	{Name: "Экваториальная Гвинея", Code: "GQ"},
	{Name: "Birma (Myanmar)", Code: "MM"},
	{Name: "Islas Vírgenes de los Estados Unidos", Code: "VI"},
	{Name: "Soudan", Code: "SD"},
	{Name: "Inde", Code: "IN"},
	{Name: "Gambie", Code: "GM"},
	{Name: "Bielo-Rússia", Code: "BY"},
	{Name: "Região Administrativa Especial de Macau", Code: "MO"},
	{Name: "列支敦士登", Code: "LI"},
	{Name: "哥伦比亚", Code: "CO"},
	{Name: "Gambia", Code: "GM"},
	{Name: "Niederlande", Code: "NL"},
	{Name: "Île Norfolk", Code: "NF"},
	{Name: "São Vincente e Granadinas", Code: "VC"},
	{Name: "Гуам", Code: "GU"},
	{Name: "巴勒斯坦领土", Code: "PS"},
	{Name: "科科斯群岛", Code: "CC"},
	{Name: "Südsudan", Code: "SS"},
	{Name: "Saint-Barthélémy", Code: "BL"},
	{Name: "República Popular Democrática do Laos", Code: "LA"},
	{Name: "Мэн, о-в", Code: "IM"},
	{Name: "土耳其", Code: "TR"},
	{Name: "Algerien", Code: "DZ"},
	{Name: "Slowenien", Code: "SI"},
	{Name: "エリトリア", Code: "ER"},
	{Name: "Alanda", Code: "AX"},
	{Name: "Макао", Code: "MO"},
	{Name: "直布罗陀", Code: "GI"},
	{Name: "Chile", Code: "CL"},
	{Name: "Pitcairn Islands", Code: "PN"},
	{Name: "Bhoutan", Code: "BT"},
	{Name: "República Democrática de São Tomé e Príncipe", Code: "ST"},
	{Name: "Ilhas Faroe", Code: "FO"},
	{Name: "Эфиопия", Code: "ET"},
	{Name: "ボネール、シント・ユースタティウスおよびサバ", Code: "BQ"},
	{Name: "Südkorea", Code: "KR"},
	{Name: "Staat der Vatikanstadt", Code: "VA"},
	{Name: "Spain", Code: "ES"},
	{Name: "Terres australes françaises", Code: "TF"},
	{Name: "ナウル", Code: "NR"},
	{Name: "ガーナ共和国", Code: "GH"},
	{Name: "スペイン", Code: "ES"},
	{Name: "グアム", Code: "GU"},
	{Name: "Панама", Code: "PA"},
	{Name: "几内亚比绍", Code: "GW"},
	{Name: "Argentina", Code: "AR"},
	{Name: "Síria", Code: "SY"},
	{Name: "Ямайка", Code: "JM"},
	{Name: "圣马丁", Code: "MF"},
	{Name: "Барбадос", Code: "BB"},
	{Name: "Bermuda", Code: "BM"},
	{Name: "Palestine", Code: "PS"},
	{Name: "Sudán", Code: "SD"},
	{Name: "Russie", Code: "RU"},
	{Name: "ウズベキスタン共和国", Code: "UZ"},
	{Name: "ブーベ島", Code: "BV"},
	{Name: "Paraguai", Code: "PY"},
	{Name: "圣多美和普林西比", Code: "ST"},
	{Name: "Британская территория в Индийском океане", Code: "IO"},
	{Name: "苏丹", Code: "SD"},
	{Name: "圭亚那", Code: "GY"},
	{Name: "Syrien", Code: "SY"},
	{Name: "Bolivien", Code: "BO"},
	{Name: "Mongolie", Code: "MN"},
	{Name: "アルメニア共和国", Code: "AM"},
	{Name: "ケイマン諸島", Code: "KY"},
	{Name: "科索沃", Code: "XK"},
	{Name: "马达加斯加", Code: "MG"},
	{Name: "牙买加", Code: "JM"},
	{Name: "Guinea Ecuatorial", Code: "GQ"},
	{Name: "Italia", Code: "IT"},
	{Name: "Somalie", Code: "SO"},
	{Name: "Tchad", Code: "TD"},
	{Name: "Île Bouvet", Code: "BV"},
	{Name: "Туркменистан", Code: "TM"},
	{Name: "Eritreia", Code: "ER"},
	{Name: "Russia", Code: "RU"},
	{Name: "North Korea", Code: "KP"},
	{Name: "Sudáfrica", Code: "ZA"},
	{Name: "Éthiopie", Code: "ET"},
	{Name: "Macédoine", Code: "MK"},
	{Name: "Namibie", Code: "NA"},
	{Name: "ルクセンブルグ", Code: "LU"},
	{Name: "南苏丹", Code: "SS"},
	{Name: "圣皮埃尔和密克隆", Code: "PM"},
	{Name: "Kambodscha", Code: "KH"},
	{Name: "Israël", Code: "IL"},
	{Name: "Jamaïque", Code: "JM"},
	{Name: "São Martinho", Code: "SX"},
	{Name: "科摩罗", Code: "KM"},
	{Name: "大韩民国", Code: "KR"},
	{Name: "Ehemalige jugoslawische Republik Mazedonien", Code: "MK"},
	{Name: "Siria", Code: "SY"},
	{Name: "Ilhas Cook", Code: "CK"},
	{Name: "Саудовская Аравия", Code: "SA"},
	{Name: "Saint Martin", Code: "MF"},
	{Name: "Wallis and Futuna", Code: "WF"},
	{Name: "サウジアラビア王国", Code: "SA"},
	{Name: "Croácia", Code: "HR"},
	{Name: "Катар", Code: "QA"},
	{Name: "瑙鲁", Code: "NR"},
	{Name: "刚果", Code: "CG"},
	{Name: "Mali", Code: "ML"},
	{Name: "Maldives", Code: "MV"},
	{Name: "Curazao", Code: "CW"},
	{Name: "チェコ共和国", Code: "CZ"},
	{Name: "グリーンランド", Code: "GL"},
	{Name: "南極", Code: "AQ"},
	{Name: "赫德与麦克唐纳群岛", Code: "HM"},
	{Name: "Südafrika", Code: "ZA"},
	{Name: "St. Martin", Code: "MF"},
	{Name: "Arabia Saudí", Code: "SA"},
	{Name: "Philippines", Code: "PH"},
	{Name: "Grecia", Code: "GR"},
	{Name: "マカオ", Code: "MO"},
	{Name: "セントクリストファー・ネビス", Code: "KN"},
	{Name: "Tunísia", Code: "TN"},
	{Name: "Republic of Korea", Code: "KR"},
	{Name: "Mauricio", Code: "MU"},
	{Name: "República Checa", Code: "CZ"},
	{Name: "仏領サン・マルタン", Code: "MF"},
	{Name: "Sierra Leona", Code: "SL"},
	{Name: "Norvège", Code: "NO"},
	{Name: "Гренада", Code: "GD"},
	{Name: "Solomon Islands", Code: "SB"},
	{Name: "大韓民国", Code: "KR"},
	{Name: "Бруней Даруссалам", Code: "BN"},
	{Name: "安哥拉", Code: "AO"},
	{Name: "多米尼加共和国", Code: "DO"},
	{Name: "蒙塞拉特群岛", Code: "MS"},
	{Name: "泽西岛", Code: "JE"},
	{Name: "Oman", Code: "OM"},
	{Name: "Ukraine", Code: "UA"},
	{Name: "Philippinen", Code: "PH"},
	{Name: "韓国、朝鮮民主主義人民共和国", Code: "KP"},
	{Name: "ツバル", Code: "TV"},
	{Name: "象牙海岸", Code: "CI"},
	{Name: "Оман", Code: "OM"},
	{Name: "Antarctica", Code: "AQ"},
	{Name: "Suazilandia", Code: "SZ"},
	{Name: "Luxemburgo", Code: "LU"},
	{Name: "Afrique du Sud", Code: "ZA"},
	{Name: "Malaisie", Code: "MY"},
	{Name: "ニューカレドニア", Code: "NC"},
	{Name: "Гаити", Code: "HT"},
	{Name: "Mosambik", Code: "MZ"},
	{Name: "Singapur", Code: "SG"},
	{Name: "Kuba", Code: "CU"},
	{Name: "Émirats Arabes Unis", Code: "AE"},
	{Name: "Шри-Ланка", Code: "LK"},
	{Name: "Лаос", Code: "LA"},
	{Name: "Зимбабве", Code: "ZW"},
	{Name: "Brasilien", Code: "BR"},
	{Name: "Nikaragua", Code: "NI"},
	{Name: "Wallis und Futuna", Code: "WF"},
	{Name: "St Kitts and Nevis", Code: "KN"},
	{Name: "Brasil", Code: "BR"},
	{Name: "ボツワナ共和国", Code: "BW"},
	{Name: "Ливан", Code: "LB"},
	{Name: "Афганистан", Code: "AF"},
	{Name: "Папуа – Новая Гвинея", Code: "PG"},
	{Name: "Jamaica", Code: "JM"},
	{Name: "Geórgia", Code: "GE"},
	{Name: "ドミニカ国", Code: "DM"},
	{Name: "Беларусь", Code: "BY"},
	{Name: "Бермудские о-ва", Code: "BM"},
	{Name: "荷兰", Code: "NL"},
	{Name: "Uganda", Code: "UG"},
	{Name: "Montserrat", Code: "MS"},
	{Name: "Cocos [Keeling] Islands", Code: "CC"},
	{Name: "Republic of the Congo", Code: "CG"},
	{Name: "クリスマス島", Code: "CX"},
	{Name: "蒙古", Code: "MN"},
	{Name: "图瓦卢", Code: "TV"},
	{Name: "Libysch-Arabische Dschamahirija", Code: "LY"},
	{Name: "Monaco", Code: "MC"},
	{Name: "Île Heard et îles McDonald", Code: "HM"},
	{Name: "Îles Malouines", Code: "FK"},
	{Name: "オーストリア共和国", Code: "AT"},
	{Name: "Исландия", Code: "IS"},
	{Name: "Malediven", Code: "MV"},
	{Name: "Indonesia", Code: "ID"},
	{Name: "ナイジェリア連邦共和国", Code: "NG"},
	{Name: "Южная Корея", Code: "KR"},
	{Name: "Republic of Moldova", Code: "MD"},
	{Name: "Azerbaiyán", Code: "AZ"},
	{Name: "Islas Georgia del Sur y Sandwich del Sur", Code: "GS"},
	{Name: "Iêmen", Code: "YE"},
	{Name: "Португалия", Code: "PT"},
	{Name: "哥斯达黎加", Code: "CR"},
	{Name: "法属波利尼西亚", Code: "PF"},
	{Name: "斐济", Code: "FJ"},
	{Name: "Iceland", Code: "IS"},
	{Name: "Azerbaïdjan", Code: "AZ"},
	{Name: "Koweït", Code: "KW"},
	{Name: "Micronésie", Code: "FM"},
	{Name: "Brésil", Code: "BR"},
	{Name: "Французская Гвиана", Code: "GF"},
	{Name: "新喀里多尼亚", Code: "NC"},
	{Name: "约旦", Code: "JO"},
	{Name: "Nicaragua", Code: "NI"},
	{Name: "Îles Caïmans", Code: "KY"},
	{Name: "モルドバ共和国", Code: "MD"},
	{Name: "インドネシア共和国", Code: "ID"},
	{Name: "Лесото", Code: "LS"},
	{Name: "Конго", Code: "CG"},
	{Name: "Фарерские о-ва", Code: "FO"},
	{Name: "Индия", Code: "IN"},
	{Name: "Vanuatu", Code: "VU"},
	{Name: "Libya", Code: "LY"},
	{Name: "Djibouti", Code: "DJ"},
	{Name: "Poland", Code: "PL"},
	{Name: "Isla Christmas", Code: "CX"},
	{Name: "Martinica", Code: "MQ"},
	{Name: "Nioué", Code: "NU"},
	{Name: "Египет", Code: "EG"},
	{Name: "Tansania", Code: "TZ"},
	{Name: "Jersey", Code: "JE"},
	{Name: "Argelia", Code: "DZ"},
	{Name: "Guayana Francesa", Code: "GF"},
	{Name: "México", Code: "MX"},
	{Name: "コモロ・イスラム連邦共和国", Code: "KM"},
	{Name: "南アフリカ", Code: "ZA"},
	{Name: "中非共和国", Code: "CF"},
	{Name: "Kenia", Code: "KE"},
	{Name: "Greece", Code: "GR"},
	{Name: "Tailandia", Code: "TH"},
	{Name: "ブルキナファソ", Code: "BF"},
	{Name: "Camarões", Code: "CM"},
	{Name: "Tadschikistan", Code: "TJ"},
	{Name: "Гвинея", Code: "GN"},
	{Name: "Turcomenistão", Code: "TM"},
	{Name: "Zentralafrikanische Republik", Code: "CF"},
	{Name: "Togo", Code: "TG"},
	{Name: "Svalbard und Jan Mayen", Code: "SJ"},
	{Name: "Swaziland", Code: "SZ"},
	{Name: "Cambodia", Code: "KH"},
	{Name: "Ucrania", Code: "UA"},
	{Name: "Îles Salomon", Code: "SB"},
	{Name: "布基纳法索", Code: "BF"},
	{Name: "Estland", Code: "EE"},
	{Name: "Iraq", Code: "IQ"},
	{Name: "キリバス共和国", Code: "KI"},
	{Name: "厄立特里亚", Code: "ER"},
	{Name: "尼泊尔", Code: "NP"},
	{Name: "ベルギー王国", Code: "BE"},
	{Name: "Schweden", Code: "SE"},
	{Name: "Marshall-Inseln", Code: "MH"},
	{Name: "Australia", Code: "AU"},
	{Name: "Lituanie", Code: "LT"},
	{Name: "Cameroun", Code: "CM"},
	{Name: "イスラエル国", Code: "IL"},
	{Name: "オーランド諸島", Code: "AX"},
	{Name: "Suazilândia", Code: "SZ"},
	{Name: "Neukaledonien", Code: "NC"},
	{Name: "Äquatorialguinea", Code: "GQ"},
	{Name: "Armenia", Code: "AM"},
	{Name: "British Virgin Islands", Code: "VG"},
	{Name: "Albanie", Code: "AL"},
	{Name: "Bénin", Code: "BJ"},
	{Name: "Ilha Bouvet", Code: "BV"},
	{Name: "Niue", Code: "NU"},
	{Name: "Zimbabwe", Code: "ZW"},
	{Name: "Libia", Code: "LY"},
	{Name: "Libye", Code: "LY"},
	{Name: "オマーン国", Code: "OM"},
	{Name: "Índia", Code: "IN"},
	{Name: "毛里求斯", Code: "MU"},
	{Name: "Belgium", Code: "BE"},
	{Name: "Corée du Sud", Code: "KR"},
	{Name: "Внешние малые острова (США)", Code: "UM"},
	{Name: "瓦利斯和富图纳", Code: "WF"},
	{Name: "Finnland", Code: "FI"},
	{Name: "Nördliche Marianen", Code: "MP"},
	{Name: "South Sudan", Code: "SS"},
	{Name: "米領太平洋諸島", Code: "UM"},
	{Name: "Marrocos", Code: "MA"},
	{Name: "Гвинея-Биссау", Code: "GW"},
	{Name: "Остров Святой Елены", Code: "SH"},
	{Name: "Armenien", Code: "AM"},
	{Name: "Kaimaninseln", Code: "KY"},
	{Name: "Svalbard y Jan Mayen", Code: "SJ"},
	{Name: "Îles Mariannes du Nord", Code: "MP"},
	{Name: "ナミビア共和国", Code: "NA"},
	{Name: "基里巴斯", Code: "KI"},
	{Name: "几内亚", Code: "GN"},
	{Name: "Qatar", Code: "QA"},
	{Name: "Britische Jungferninseln", Code: "VG"},
	{Name: "Islas Cocos", Code: "CC"},
	{Name: "Bermudes", Code: "BM"},
	{Name: "ジャージー", Code: "JE"},
	{Name: "Grécia", Code: "GR"},
	{Name: "Фиджи", Code: "FJ"},
	{Name: "Estonia", Code: "EE"},
	{Name: "Gabon", Code: "GA"},
	{Name: "ルワンダ共和国", Code: "RW"},
	{Name: "Guiné Equatorial", Code: "GQ"},
	{Name: "Алжир", Code: "DZ"},
	{Name: "沙特阿拉伯", Code: "SA"},
	{Name: "台湾", Code: "TW"},
	{Name: "São Tomé-et-Príncipe", Code: "ST"},
	{Name: "Grenade", Code: "GD"},
	{Name: "マダガスカル共和国", Code: "MG"},
	{Name: "Фолклендские о-ва", Code: "FK"},
	{Name: "Romania", Code: "RO"},
	{Name: "Norfolk Island", Code: "NF"},
	{Name: "Etiopía", Code: "ET"},
	{Name: "Jordanie", Code: "JO"},
	{Name: "ソマリア", Code: "SO"},
	{Name: "诺福克岛", Code: "NF"},
	{Name: "Turkmenistán", Code: "TM"},
	{Name: "Haití", Code: "HT"},
	{Name: "ホンジュラス共和国", Code: "HN"},
	{Name: "Paquistão", Code: "PK"},
	{Name: "Isla Norfolk", Code: "NF"},
	{Name: "Comores", Code: "KM"},
	{Name: "Sénégal", Code: "SN"},
	{Name: "マケドニア旧ユーゴスラビア共和国", Code: "MK"},
	{Name: "Morocco", Code: "MA"},
	{Name: "Bolivia", Code: "BO"},
	{Name: "ローマ法王庁 (バチカン市国)", Code: "VA"},
	{Name: "カーボベルデ", Code: "CV"},
	{Name: "Costa Rica", Code: "CR"},
	{Name: "Судан", Code: "SD"},
	{Name: "阿根廷", Code: "AR"},
	{Name: "Uzbekistan", Code: "UZ"},
	{Name: "Isla Niue", Code: "NU"},
	{Name: "Argentine", Code: "AR"},
	{Name: "アラブ首長国連邦", Code: "AE"},
	{Name: "Кот-д'Ивуар", Code: "CI"},
	{Name: "Токелау", Code: "TK"},
	{Name: "孟加拉", Code: "BD"},
	{Name: "country_name", Code: "country_iso_code"},
	{Name: "Congo-Brazzaville", Code: "CG"},
	{Name: "アンゴラ共和国", Code: "AO"},
	{Name: "トンガ王国", Code: "TO"},
	{Name: "Джерси", Code: "JE"},
	{Name: "白俄罗斯", Code: "BY"},
	{Name: "Weihnachtsinsel", Code: "CX"},
	{Name: "Marokko", Code: "MA"},
	{Name: "Палестинские территории", Code: "PS"},
	{Name: "Доминиканская Республика", Code: "DO"},
	{Name: "摩尔多瓦共和国", Code: "MD"},
	{Name: "英属维京群岛", Code: "VG"},
	{Name: "Liberia", Code: "LR"},
	{Name: "Guinea-Bissau", Code: "GW"},
	{Name: "Islas menores alejadas de los Estados Unidos", Code: "UM"},
	{Name: "Turquia", Code: "TR"},
	{Name: "Тонга", Code: "TO"},
	{Name: "斯里兰卡", Code: "LK"},
	{Name: "伯利兹", Code: "BZ"},
	{Name: "New Zealand", Code: "NZ"},
	{Name: "Camerún", Code: "CM"},
	{Name: "Égypte", Code: "EG"},
	{Name: "Bolivie", Code: "BO"},
	{Name: "法属南部领土", Code: "TF"},
	{Name: "奥地利", Code: "AT"},
	{Name: "Rumänien", Code: "RO"},
	{Name: "Reino Unido", Code: "GB"},
	{Name: "Japon", Code: "JP"},
	{Name: "グアドループ", Code: "GP"},
	{Name: "Либерия", Code: "LR"},
	{Name: "坦桑尼亚", Code: "TZ"},
	{Name: "Andorra", Code: "AD"},
	{Name: "Bosnia and Herzegovina", Code: "BA"},
	{Name: "Wallis y Futuna", Code: "WF"},
	{Name: "スワジランド王国", Code: "SZ"},
	{Name: "ブルネイ", Code: "BN"},
	{Name: "Белиз", Code: "BZ"},
	{Name: "墨西哥", Code: "MX"},
	{Name: "Остров Святого Мартина", Code: "MF"},
	{Name: "Ägypten", Code: "EG"},
	{Name: "Guadeloupe", Code: "GP"},
	{Name: "Rumanía", Code: "RO"},
	{Name: "Benín", Code: "BJ"},
	{Name: "Уганда", Code: "UG"},
	{Name: "Албания", Code: "AL"},
	{Name: "Сингапур", Code: "SG"},
	{Name: "Синт-Мартен", Code: "SX"},
	{Name: "Papouasie-Nouvelle Guinée", Code: "PG"},
	{Name: "Guinée-Bissau", Code: "GW"},
	{Name: "ノルウェー王国", Code: "NO"},
	{Name: "Omã", Code: "OM"},
	{Name: "Ilhas Comores", Code: "KM"},
	{Name: "Butão", Code: "BT"},
	{Name: "Ilhas Menores Distantes dos Estados Unidos", Code: "UM"},
	{Name: "Остров Святого Бартоломея", Code: "BL"},
	{Name: "Grönland", Code: "GL"},
	{Name: "Panama", Code: "PA"},
	{Name: "Ангола", Code: "AO"},
	{Name: "Камерун", Code: "CM"},
	{Name: "Ungarn", Code: "HU"},
	{Name: "Falklandinseln", Code: "FK"},
	{Name: "Cayman Islands", Code: "KY"},
	{Name: "Polinesia Francesa", Code: "PF"},
	{Name: "Malte", Code: "MT"},
	{Name: "マヨット島", Code: "YT"},
	{Name: "ベニン共和国", Code: "BJ"},
	{Name: "Népal", Code: "NP"},
	{Name: "マレーシア", Code: "MY"},
	{Name: "ЦАР", Code: "CF"},
	{Name: "格恩西岛", Code: "GG"},
	{Name: "Мексика", Code: "MX"},
	{Name: "Azerbaijan", Code: "AZ"},
	{Name: "South Africa", Code: "ZA"},
	{Name: "Mauritanie", Code: "MR"},
	{Name: "メキシコ合衆国", Code: "MX"},
	{Name: "モントセラト島", Code: "MS"},
	{Name: "Cazaquistão", Code: "KZ"},
	{Name: "Свазиленд", Code: "SZ"},
	{Name: "文莱", Code: "BN"},
	{Name: "Colombia", Code: "CO"},
	{Name: "Îles Turques-et-Caïques", Code: "TC"},
	{Name: "Territórios Franceses do Sul", Code: "TF"},
	{Name: "Эквадор", Code: "EC"},
	{Name: "Индонезия", Code: "ID"},
	{Name: "Angola", Code: "AO"},
	{Name: "Nauru", Code: "NR"},
	{Name: "Guinea", Code: "GN"},
	{Name: "Dänemark", Code: "DK"},
	{Name: "Îles Vierges des États-Unis", Code: "VI"},
	{Name: "セイシェル", Code: "SC"},
	{Name: "ガンビア共和国", Code: "GM"},
	{Name: "США", Code: "US"},
	{Name: "Vatican City", Code: "VA"},
	{Name: "Guinée", Code: "GN"},
	{Name: "Sainte-Lucie", Code: "LC"},
	{Name: "Samoa américaines", Code: "AS"},
	{Name: "赤道几内亚", Code: "GQ"},
	{Name: "意大利", Code: "IT"},
	{Name: "Island", Code: "IS"},
	{Name: "Kroatien", Code: "HR"},
	{Name: "Turks- und Caicosinseln", Code: "TC"},
	{Name: "Serbie", Code: "RS"},
	{Name: "シンガポール", Code: "SG"},
	{Name: "Sri Lanka", Code: "LK"},
	{Name: "Vereinigtes Königreich", Code: "GB"},
	{Name: "Georgia", Code: "GE"},
	{Name: "Emirados Árabes Unidos", Code: "AE"},
	{Name: "Itália", Code: "IT"},
	{Name: "老挝人民民主共和国", Code: "LA"},
	{Name: "Amerikanische Jungferninseln", Code: "VI"},
	{Name: "Saint Helena", Code: "SH"},
	{Name: "レユニオン島", Code: "RE"},
	{Name: "França", Code: "FR"},
	{Name: "Бахрейн", Code: "BH"},
	{Name: "尼加拉瓜", Code: "NI"},
	{Name: "Moldau (Republik Moldau)", Code: "MD"},
	{Name: "Syria", Code: "SY"},
	{Name: "Norway", Code: "NO"},
	{Name: "Западная Сахара", Code: "EH"},
	{Name: "苏里南", Code: "SR"},
	{Name: "Непал", Code: "NP"},
	{Name: "Jemen", Code: "YE"},
	{Name: "Kiribati", Code: "KI"},
	{Name: "Ghana", Code: "GH"},
	{Name: "Iran", Code: "IR"},
	{Name: "Filipinas", Code: "PH"},
	{Name: "ロシア", Code: "RU"},
	{Name: "アフガニスタン・イスラム国", Code: "AF"},
	{Name: "托克劳", Code: "TK"},
	{Name: "Madagascar", Code: "MG"},
	{Name: "スロベニア", Code: "SI"},
	{Name: "Ilhas Salomão", Code: "SB"},
	{Name: "Jordanien", Code: "JO"},
	{Name: "Kuwait", Code: "KW"},
	{Name: "Antigua y Barbuda", Code: "AG"},
	{Name: "Гамбия", Code: "GM"},
	{Name: "格林纳达", Code: "GD"},
	{Name: "巴拿马", Code: "PA"},
	{Name: "Schweiz", Code: "CH"},
	{Name: "Amerikanisch-Ozeanien", Code: "UM"},
	{Name: "Francia", Code: "FR"},
	{Name: "北マリアナ諸島", Code: "MP"},
	{Name: "Colômbia", Code: "CO"},
	{Name: "Сальвадор", Code: "SV"},
	{Name: "拉脱维亚", Code: "LV"},
	{Name: "San Martín", Code: "SX"},
	{Name: "フィジー", Code: "FJ"},
	{Name: "シエラレオネ", Code: "SL"},
	{Name: "ドイツ連邦共和国", Code: "DE"},
	{Name: "Сент-Люсия", Code: "LC"},
	{Name: "Гватемала", Code: "GT"},
	{Name: "秘鲁", Code: "PE"},
	{Name: "Ruanda", Code: "RW"},
	{Name: "Indien", Code: "IN"},
	{Name: "Japan", Code: "JP"},
	{Name: "Uzbequistão", Code: "UZ"},
	{Name: "Боливия", Code: "BO"},
	{Name: "吉布提", Code: "DJ"},
	{Name: "科威特", Code: "KW"},
	{Name: "Литва", Code: "LT"},
	{Name: "Aserbaidschan", Code: "AZ"},
	{Name: "Irland", Code: "IE"},
	{Name: "Martinique", Code: "MQ"},
	{Name: "East Timor", Code: "TL"},
	{Name: "Cuba", Code: "CU"},
	{Name: "Omán", Code: "OM"},
	{Name: "Армения", Code: "AM"},
	{Name: "Afeganistão", Code: "AF"},
	{Name: "Gronelândia", Code: "GL"},
	{Name: "Katar", Code: "QA"},
	{Name: "Insel Man", Code: "IM"},
	{Name: "Peru", Code: "PE"},
	{Name: "Western Sahara", Code: "EH"},
	{Name: "Perú", Code: "PE"},
	{Name: "Bangladexe", Code: "BD"},
	{Name: "Suíça", Code: "CH"},
	{Name: "Италия", Code: "IT"},
	{Name: "Frankreich", Code: "FR"},
	{Name: "Kyrgyzstan", Code: "KG"},
	{Name: "多米尼加", Code: "DM"},
	{Name: "Zimbábue", Code: "ZW"},
	{Name: "Irak", Code: "IQ"},
	{Name: "Thailand", Code: "TH"},
	{Name: "Тринидад и Тобаго", Code: "TT"},
	{Name: "Benin", Code: "BJ"},
	{Name: "Honduras", Code: "HN"},
	{Name: "Santa Elena", Code: "SH"},
	{Name: "Santa Lucía", Code: "LC"},
	{Name: "Macedônia", Code: "MK"},
	{Name: "Gâmbia", Code: "GM"},
	{Name: "Бутан", Code: "BT"},
	{Name: "库克群岛", Code: "CK"},
	{Name: "福克兰群岛", Code: "FK"},
	{Name: "西サモア", Code: "WS"},
	{Name: "Seychellen", Code: "SC"},
	{Name: "Fiji", Code: "FJ"},
	{Name: "Jordania", Code: "JO"},
	{Name: "Nueva Zelanda", Code: "NZ"},
	{Name: "Dinamarca", Code: "DK"},
	{Name: "Islas Caimán", Code: "KY"},
	{Name: "コソボ", Code: "XK"},
	{Name: "Jordânia", Code: "JO"},
	{Name: "Laos", Code: "LA"},
	{Name: "Lebanon", Code: "LB"},
	{Name: "ブルンジ共和国", Code: "BI"},
	{Name: "リトアニア共和国", Code: "LT"},
	{Name: "ガボン共和国", Code: "GA"},
	{Name: "アイルランド", Code: "IE"},
	{Name: "São Bartolomeu", Code: "BL"},
	{Name: "Lesotho", Code: "LS"},
	{Name: "Territorio Británico del Océano Índico", Code: "IO"},
	{Name: "Île de Man", Code: "IM"},
	{Name: "Equador", Code: "EC"},
	{Name: "Тувалу", Code: "TV"},
	{Name: "卡塔尔", Code: "QA"},
	{Name: "Malaysia", Code: "MY"},
	{Name: "Saint Kitts und Nevis", Code: "KN"},
	{Name: "Mauritânia", Code: "MR"},
	{Name: "Маврикий", Code: "MU"},
	{Name: "Андорра", Code: "AD"},
	{Name: "Канада", Code: "CA"},
	{Name: "圣马力诺", Code: "SM"},
	{Name: "Jamaika", Code: "JM"},
	{Name: "Congo [República]", Code: "CG"},
	{Name: "Wallis-et-Futuna", Code: "WF"},
	{Name: "Финляндия", Code: "FI"},
	{Name: "西班牙", Code: "ES"},
	{Name: "Mauritania", Code: "MR"},
	{Name: "Roumanie", Code: "RO"},
	{Name: "タジキスタン共和国", Code: "TJ"},
	{Name: "アルゼンチン共和国", Code: "AR"},
	{Name: "グレナダ", Code: "GD"},
	{Name: "ニウエ島", Code: "NU"},
	{Name: "Malauí", Code: "MW"},
	{Name: "Guam", Code: "GU"},
	{Name: "Corea del Sur", Code: "KR"},
	{Name: "Свальбард и Ян-Майен", Code: "SJ"},
	{Name: "Afghanistan", Code: "AF"},
	{Name: "Comoras", Code: "KM"},
	{Name: "Мадагаскар", Code: "MG"},
	{Name: "摩纳哥", Code: "MC"},
	{Name: "Guyana", Code: "GY"},
	{Name: "Estados Unidos", Code: "US"},
	{Name: "Corée du Nord", Code: "KP"},
	{Name: "Sérvia", Code: "RS"},
	{Name: "Alemanha", Code: "DE"},
	{Name: "Ilhas Caiman", Code: "KY"},
	{Name: "爱尔兰", Code: "IE"},
	{Name: "Burundi", Code: "BI"},
	{Name: "San Vicente y las Granadinas", Code: "VC"},
	{Name: "Того", Code: "TG"},
	{Name: "芬兰", Code: "FI"},
	{Name: "Haiti", Code: "HT"},
	{Name: "Czechia", Code: "CZ"},
	{Name: "Ilhas Wallis e Futuna", Code: "WF"},
	{Name: "萨摩亚", Code: "WS"},
	{Name: "Bonaire, Sint Eustatius, and Saba", Code: "BQ"},
	{Name: "Bermudas", Code: "BM"},
	{Name: "チャド共和国", Code: "TD"},
	{Name: "Polônia", Code: "PL"},
	{Name: "Trindade e Tobago", Code: "TT"},
	{Name: "圣赫勒拿", Code: "SH"},
	{Name: "百慕大", Code: "BM"},
	{Name: "Saudi Arabia", Code: "SA"},
	{Name: "Islas de Åland", Code: "AX"},
	{Name: "タイ王国", Code: "TH"},
	{Name: "ハイチ共和国", Code: "HT"},
	{Name: "Грузия", Code: "GE"},
	{Name: "Венесуэла", Code: "VE"},
	{Name: "法国", Code: "FR"},
	{Name: "Гайана", Code: "GY"},
	{Name: "Túnez", Code: "TN"},
	{Name: "Finlande", Code: "FI"},
	{Name: "パラオ", Code: "PW"},
	{Name: "ベトナム", Code: "VN"},
	{Name: "Iraque", Code: "IQ"},
	{Name: "Quirguistão", Code: "KG"},
	{Name: "República Democrática de Timor-Leste", Code: "TL"},
	{Name: "肯尼亚", Code: "KE"},
	{Name: "马拉维", Code: "MW"},
	{Name: "Weißrussland", Code: "BY"},
	{Name: "Macao", Code: "MO"},
	{Name: "Monténégro", Code: "ME"},
	{Name: "Gabão", Code: "GA"},
	{Name: "Uruguai", Code: "UY"},
	{Name: "Россия", Code: "RU"},
	{Name: "Вьетнам", Code: "VN"},
	{Name: "Islas Marshall", Code: "MH"},
	{Name: "Zambie", Code: "ZM"},
	{Name: "Нигер", Code: "NE"},
	{Name: "Остров Буве", Code: "BV"},
	{Name: "巴巴多斯", Code: "BB"},
}
